# GENERATED by studio/tools/sync-engine.sh from clipforge/clipforge/alignment.py.
# Do not edit it: change the source and run the script. `sync-engine.sh --check` fails on drift.
"""
Forced alignment (scope S0): re-time Hammy's word text against the audio.

Hammy's word start/end are raw ASR estimates (±50-200ms wobble, quantized to a
0.02s grid). This re-pins each word to the waveform sample-accurately using
torchaudio's CTC forced alignment (MMS_FA / wav2vec2), so the ~16% of cuts with
no nearby silence and the editor's click-word-to-cut land on the true word edge.
The word TEXT is never changed; only the timings are corrected.

Heavy path: needs torchaudio + a one-time ~1.2GB wav2vec2 model download.
Imported lazily so the rest of clipforge runs without it. Long audio is aligned
in windows (a single 14-min transformer pass would blow up attention memory),
and word ends are clamped at measured silence to kill CTC's trailing-silence
over-extension (a word followed by a pause otherwise stretches to the next word).
"""

from __future__ import annotations

import re
import subprocess
from pathlib import Path

# Chars the MMS_FA tokenizer understands (lowercase latin + apostrophe).
_KEEP = re.compile(r"[^a-z']")


def normalize_word(word: str) -> str:
    """Lowercase and strip to the aligner's charset; '' if nothing alignable."""
    return _KEEP.sub("", word.lower()).strip("'")


def _decode_segment(path: Path | str, sr: int, start: float = 0.0,
                    dur: float | None = None):
    """Decode an audio/video span to a 1-D float32 torch tensor at `sr`, mono.

    torchaudio 2.11 dropped its native decoders (needs torchcodec); we already
    shell ffmpeg for silence detection, so reuse it here instead of a new dep.
    """
    import numpy as np
    import torch

    cmd = ["ffmpeg", "-hide_banner", "-nostats"]
    if start:
        cmd += ["-ss", str(start)]
    cmd += ["-i", str(path)]
    if dur is not None:
        cmd += ["-t", str(dur)]
    cmd += ["-f", "f32le", "-ac", "1", "-ar", str(sr), "-"]
    proc = subprocess.run(cmd, capture_output=True)
    if proc.returncode != 0:
        raise RuntimeError(f"ffmpeg decode failed: {proc.stderr[-300:]!r}")
    audio = np.frombuffer(proc.stdout, dtype=np.float32).copy()
    return torch.from_numpy(audio).unsqueeze(0)  # [1, N]


def _load_aligner(device: str | None):
    """Load the MMS_FA model/tokenizer/aligner once; return (bundle, parts, device)."""
    import torch
    import torchaudio

    if device is None:
        device = "mps" if torch.backends.mps.is_available() else "cpu"
    bundle = torchaudio.pipelines.MMS_FA
    model = bundle.get_model().to(device)
    return bundle, model, bundle.get_tokenizer(), bundle.get_aligner(), device


def _align_window(model, tokenizer, aligner, device, waveform, transcript, sr):
    """Forced-align one decoded window; return [(start_s, end_s), ...] per word."""
    import torch

    with torch.inference_mode():
        emission, _ = model(waveform.to(device))
        # torchaudio's forced_align op has no MPS kernel; run that step on CPU.
        token_spans = aligner(emission[0].cpu(), tokenizer(transcript))
    ratio = waveform.size(1) / emission.size(1)
    return [(s[0].start * ratio / sr, s[-1].end * ratio / sr) for s in token_spans]


def _clamp_ends_to_silence(words: list[dict], silences) -> None:
    """Trim each word's end back to the next measured silence (in place).

    Kills CTC's trailing-silence over-extension: a word followed by a pause
    otherwise stretches its end across the gap to the next word. We pull the end
    back to where the audio actually goes quiet.
    """
    sil_starts = sorted(s.start for s in silences)
    import bisect
    for w in words:
        if "start" not in w or "end" not in w:
            continue
        j = bisect.bisect_right(sil_starts, w["start"])
        if j < len(sil_starts) and sil_starts[j] < w["end"]:
            w["end"] = round(max(w["start"], sil_starts[j]), 3)


def align_words(
    audio_path: Path | str,
    words: list[dict],
    device: str | None = None,
    max_seconds: float | None = None,
    window_s: float = 40.0,
    pad_s: float = 2.0,
    silences=None,
) -> list[dict]:
    """Return `words` with start/end re-timed to the audio (text unchanged).

    Aligns in `window_s` windows (decoded with `pad_s` tail padding so a word at
    a window edge isn't clipped), assigning each word to the window its start
    falls in. Event tokens and pure-punctuation words keep their original timing.
    If `silences` is given, word ends are clamped to the next silence.

    Args:
        audio_path: Audio or video file.
        words: Hammy word list (load_words).
        device: "mps" | "cpu" | None (auto: mps if available else cpu).
        max_seconds: Only align words starting before this (tracer/tests).
        window_s: Alignment window length in seconds.
        pad_s: Extra audio decoded past each window so edge words have room.
        silences: Optional list of audio_boundaries.Silence for end-clamping.
    """
    out = [dict(w) for w in words]
    speech = [
        (i, w) for i, w in enumerate(words)
        if w.get("type") != "event" and "start" in w and "end" in w
        and normalize_word(str(w.get("word", "")))
        and (max_seconds is None or w["start"] < max_seconds)
    ]
    if not speech:
        return out

    bundle, model, tokenizer, aligner, device = _load_aligner(device)
    sr = bundle.sample_rate
    t_end = max(w["end"] for _, w in speech)
    if max_seconds is not None:
        t_end = min(t_end, max_seconds)

    t = 0.0
    while t < t_end:
        t1 = min(t + window_s, t_end)
        win = [(i, w) for i, w in speech if t <= w["start"] < t1]
        if win:
            transcript = [normalize_word(str(w["word"])) for _, w in win]
            dur = (t1 - t) + pad_s
            waveform = _decode_segment(audio_path, sr, start=t, dur=dur)
            times = _align_window(model, tokenizer, aligner, device, waveform, transcript, sr)
            for (i, _), (s, e) in zip(win, times):
                out[i]["start"] = round(t + s, 3)
                out[i]["end"] = round(t + e, 3)
        t = t1

    if silences is not None:
        _clamp_ends_to_silence(out, silences)
    return out
