# GENERATED by studio/tools/sync-engine.sh from clipforge/clipforge/audio_boundaries.py.
# Do not edit it: change the source and run the script. `sync-engine.sh --check` fails on drift.
"""
Audio-first cut boundaries (scope S0).

ClipForge's cuts have always come from transcription WORD timestamps, which
wobble +-50-200ms and butt-join most words (no inter-word gap to cut into). The
real silence -- breaths, word-tails, micro-pauses -- lives only in the audio
signal. This module reads that signal so cuts can land in measured silence
instead of mid-word.

Build order (see specs/S0-audio-first.md):
  v0  silence detection via ffmpeg `silencedetect`   <- this file, step 1
      forced alignment (.aligned.words.json)
      audio-aware snap replacing the timestamp-gap no-op
      frame-accurate render edge
"""

from __future__ import annotations

import re
import subprocess
from dataclasses import dataclass
from pathlib import Path


@dataclass(frozen=True)
class Silence:
    """A measured silent interval, in source-time seconds."""

    start: float
    end: float

    @property
    def duration(self) -> float:
        return self.end - self.start

    def contains(self, t: float) -> bool:
        return self.start <= t <= self.end


_SILENCE_START_RE = re.compile(r"silence_start:\s*(-?\d+\.?\d*)")
_SILENCE_END_RE = re.compile(r"silence_end:\s*(-?\d+\.?\d*)")

# Default detection sensitivity. These are the single source of truth for the
# whole pipeline (pipeline._silences_for and the /api/silences route resolve to
# these unless a caller overrides). They were retuned from a too-conservative
# -30 dB / 0.08 s that missed real dead-air, breaths and word-tails:
#
#   * DEFAULT_NOISE_DB = -25 dB — softer floor. silencedetect flags audio whose
#     PEAK sits below this; at -30 a soft pause/breath in the -25..-30 dBFS band
#     reads as speech and is missed. -25 catches those without reaching the
#     -20 "everything is a pause" extreme.
#   * DEFAULT_MIN_SILENCE = 0.05 s — catches genuine 50-80 ms gaps (short
#     breaths, word-tails) the old 0.08 s ignored, while staying well above
#     plosive-gap territory (~10-30 ms) so we don't flag every stop consonant.
#
# Both stay caller-overridable so a future UI slider can drive them.
DEFAULT_NOISE_DB = -25.0
DEFAULT_MIN_SILENCE = 0.05

# Cushion (seconds) left on the kept side of a clamped cut edge so it never sits
# exactly on a voicing onset/offset. Single source of truth for the whole
# word-clip layer: microcut_pacing imports this (it already imports the word-edge
# helpers from here), so both the snap path and the micro-cut path share one
# value. DRY: the literals that used to read 0.005 in two places now read this.
SILENCE_SAFETY = 0.005


def detect_silences(
    audio_path: Path | str,
    noise_db: float = DEFAULT_NOISE_DB,
    min_silence: float = DEFAULT_MIN_SILENCE,
) -> list[Silence]:
    """Find silent intervals in an audio/video file via ffmpeg `silencedetect`.

    Reads the ACTUAL waveform, not the transcription timestamps. This is the
    signal the word stamps can't see: on #4, 84% of adjacent words are
    butt-joined (zero inter-word gap), yet the audio has real silence in those
    spans (breaths, word-tails). Those are where a cut can land cleanly.

    Args:
        audio_path: Audio or video file (ffmpeg reads either).
        noise_db: Anything quieter than this (dBFS) counts as silence. The
            default -25 dB catches soft pauses/breaths; toward -40 catches only
            deep silence, toward -20 catches even softer pauses.
        min_silence: Ignore silences shorter than this (seconds). The default
            0.05s catches a short breath/word-tail without flagging every
            plosive gap.

    Returns:
        Silent intervals sorted by start time.
    """
    af = f"silencedetect=noise={noise_db}dB:d={min_silence}"
    cmd = [
        "ffmpeg", "-hide_banner", "-nostats",
        "-i", str(audio_path),
        "-af", af,
        "-f", "null", "-",
    ]
    # silencedetect writes its report to stderr; the null muxer discards audio.
    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.returncode != 0:
        raise RuntimeError(
            f"ffmpeg silencedetect failed ({result.returncode}): "
            f"{result.stderr[-500:]}"
        )
    return _parse_silencedetect(result.stderr)


def _parse_silencedetect(stderr: str) -> list[Silence]:
    """Pair silence_start / silence_end lines from ffmpeg stderr into intervals."""
    silences: list[Silence] = []
    pending_start: float | None = None
    for line in stderr.splitlines():
        m = _SILENCE_START_RE.search(line)
        if m:
            pending_start = max(0.0, float(m.group(1)))
            continue
        m = _SILENCE_END_RE.search(line)
        if m and pending_start is not None:
            silences.append(Silence(start=pending_start, end=float(m.group(1))))
            pending_start = None
    silences.sort(key=lambda s: s.start)
    return silences


# ── Proof / measurement: silence the word timestamps under-report ────────────

@dataclass
class HiddenSilenceReport:
    """How much real silence the word timestamps miss.

    The core S0 claim, made measurable: at boundaries the transcript marks as
    continuous speech (small or zero inter-word gap), the audio still has
    silence to cut into. If this report is non-empty, the timestamp-only snap
    is provably blind there.
    """

    boundaries_checked: int
    zero_gap_boundaries: int               # consecutive words butt-joined (gap == 0)
    hidden_at_zero_gap: int                # zero-gap boundaries with real audio silence
    hidden_seconds: float                  # total silence the stamps reported as ~0 gap
    examples: list[tuple[float, float, float]]  # (boundary_t, gap_s, silence_dur)


def hidden_silence_at_boundaries(
    silences: list[Silence],
    words: list[dict],
    gap_eps: float = 0.05,
) -> HiddenSilenceReport:
    """Cross-reference measured silences against inter-word timestamp gaps.

    For each consecutive speech-word pair, the transcript reports a gap of
    `next.start - prev.end`. We check whether a measured silence sits on that
    boundary and is longer than the reported gap -- i.e. the audio knows about
    silence the timestamps don't. `gap_eps` (default 0.05s, matching
    longform.snap_user_cuts_to_gaps' min_gap) is the threshold under which the
    existing snap is a no-op.

    Args:
        silences: Output of detect_silences().
        words: Hammy word list (load_words). Event tokens are skipped.
        gap_eps: Inter-word gaps at or below this count as "no gap" for the snap.

    Returns:
        A HiddenSilenceReport.
    """
    speech = [w for w in words if w.get("type") != "event" and "start" in w and "end" in w]
    speech.sort(key=lambda w: w["start"])

    boundaries = 0
    zero_gap = 0
    hidden = 0
    hidden_seconds = 0.0
    examples: list[tuple[float, float, float]] = []

    for prev, nxt in zip(speech, speech[1:]):
        gap = nxt["start"] - prev["end"]
        if gap > gap_eps:
            boundaries += 1
            continue
        # This boundary is "no gap" as far as the snap is concerned.
        boundaries += 1
        zero_gap += 1
        boundary_t = prev["end"]
        sil = next((s for s in silences if s.contains(boundary_t)), None)
        if sil is not None and sil.duration > max(gap, 0.0):
            hidden += 1
            hidden_seconds += sil.duration
            if len(examples) < 8:
                examples.append((round(boundary_t, 3), round(gap, 3), round(sil.duration, 3)))

    return HiddenSilenceReport(
        boundaries_checked=boundaries,
        zero_gap_boundaries=zero_gap,
        hidden_at_zero_gap=hidden,
        hidden_seconds=round(hidden_seconds, 2),
        examples=examples,
    )


# ── The audio-aware snap (replaces longform.snap_user_cuts_to_gaps) ───────────

def nearest_silence(
    t: float, silences: list[Silence], window: float
) -> Silence | None:
    """The silence interval closest to time `t`, or None if none within `window`.

    Distance is 0 when `t` is inside the interval. `silences` need not be
    sorted; this is a linear scan (cut counts are small).
    """
    best: Silence | None = None
    best_d = window
    for s in silences:
        if s.contains(t):
            return s
        d = s.start - t if t < s.start else t - s.end
        if d <= best_d:
            best_d = d
            best = s
    return best


# ── Word-clip safety (shared with microcut_pacing) ────────────────────────────
# The invariant that must hold at EVERY cut level: a cut edge never lands
# strictly INSIDE a spoken word. A measured silence can reach a little way into a
# word -- forced-alignment wobble, or a soft consonant onset/tail (s/sh/f/th/h)
# that drops below the -25 dB floor and reads as quiet -- so snapping a cut edge
# onto that silence would clip the word ("see" -> "ee"). These primitives pull
# an edge back out of any word it lands inside, to the word's boundary, so the
# word is kept whole. The micro-cut pacing path (microcut_pacing) imports them
# too, so the guarantee is GLOBAL, not per-path. ``_word_spans`` is SPEECH ONLY
# (the onset grid in refine_onsets relies on that), so vocalization events
# (laughter/gasps, ``type == "event"``) are kept whole on the snap path via the
# separate ``_protected_spans`` used ONLY for that path's word-clip clamp.


def _word_spans(words: list[dict]) -> list[tuple[float, float]]:
    """Sorted (start, end) spans of spoken words; vocalization events excluded."""
    return sorted(
        (float(w["start"]), float(w["end"]))
        for w in words
        if w.get("type") != "event" and "start" in w and "end" in w
    )


def _event_spans(words: list[dict]) -> list[tuple[float, float]]:
    """Sorted (start, end) spans of vocalization events (``type == "event"``)."""
    return sorted(
        (float(w["start"]), float(w["end"]))
        for w in words
        if w.get("type") == "event" and "start" in w and "end" in w
    )


def _protected_spans(words: list[dict]) -> list[tuple[float, float]]:
    """Word + event spans (sorted) the SNAP-PATH clamp must keep whole.

    A soft vocalization event (a sigh/gasp/laugh) can carry interior silence the
    snap would otherwise land an edge inside -- clipping the event just as a soft
    consonant onset clips a word. So the snap-path word-clip clamp protects events
    too. This is kept SEPARATE from ``_word_spans`` (speech-only) because the
    onset-refine grid intentionally excludes events; only the snap clamp uses
    this combined set. The ``_inside_word`` / ``_containing_word`` scan tolerates
    the (rare) event-overlaps-word case: spans are sorted by start, and the scan
    checks every span whose start precedes ``t``.
    """
    return sorted(_word_spans(words) + _event_spans(words))


def _inside_word(t: float, spans: list[tuple[float, float]]) -> bool:
    """True if ``t`` falls strictly inside a spoken word (would clip it)."""
    for s, e in spans:
        if s < t < e:
            return True
        if s > t:  # spans sorted; no later span can contain t
            break
    return False


def _containing_word(
    t: float, spans: list[tuple[float, float]]
) -> tuple[float, float] | None:
    """The spoken word ``t`` falls strictly inside, or None. Spans are sorted."""
    for s, e in spans:
        if s < t < e:
            return (s, e)
        if s > t:
            break
    return None


def _clamp_out_of_words(
    s: float,
    e: float,
    spans: list[tuple[float, float]],
    safety: float = SILENCE_SAFETY,
) -> tuple[float, float] | None:
    """Pull the edges of ``[s, e]`` out of any word they land strictly inside.

    A cut ``[s, e]`` removes that span, so the words at its edges must survive:
    the START is pushed past the END of any word it sits in (keeps that word's
    tail), and the END is pulled before the START of any word it sits in (keeps
    that word's onset). Returns the safe ``(s, e)``, or ``None`` if the span
    collapses or still can't be made safe (e.g. one word fully spans the cut, or
    overlapping forced-aligned words leave no clean point). The shared word-clip
    backstop for both the silence-snap and micro-cut paths.
    """
    cw = _containing_word(s, spans)
    if cw is not None:
        s = cw[1] + safety
    cw = _containing_word(e, spans)
    if cw is not None:
        e = cw[0] - safety
    if e - s <= 0 or _inside_word(s, spans) or _inside_word(e, spans):
        return None
    return (s, e)


def snap_cuts_to_silence(
    cuts: list[dict],
    silences: list[Silence],
    words: list[dict] | None = None,
    window: float = 0.20,
    safety_margin: float = SILENCE_SAFETY,
) -> list[dict]:
    """Magnet each cut endpoint onto the nearest measured silence.

    The audio-first replacement for `longform.snap_user_cuts_to_gaps`. That
    one snapped to inter-word TIMESTAMP gaps, a no-op for the 84% of #4
    boundaries that are butt-joined. This snaps to where the audio is actually
    quiet, so a cut's edges land in silence instead of mid-phoneme:

      * trailing edge `end`  -> the kept material AFTER the cut should resume at
        the sound onset, i.e. the silence's END (minus a safety cushion).
      * leading edge `start` -> the kept material BEFORE the cut should stop at
        the sound offset, i.e. the silence's START (plus a safety cushion).

    When no silence sits within `window` of an edge (mid-run speech, no pause to
    hide the cut in), the edge falls back to the nearest word boundary if
    `words` is given (the old behaviour, graceful degradation), else stays put.

    Word-clip safety (global invariant): a snapped edge never lands strictly
    inside a spoken word. A measured silence can reach into a word when a soft
    consonant onset/tail drops below the noise floor and reads as quiet; the edge
    is then pulled back to that word's boundary so the word is kept whole (shared
    with microcut_pacing via `_clamp_out_of_words`). An edge that lands on
    genuine inter-word quiet is inside no word, so it stays put -- the legitimate
    audio-first snap is unchanged. Needs `words`.

    Args:
        cuts: List of {start, end, ...} removed spans in source-time seconds.
            Extra keys (e.g. 'reason') are preserved.
        silences: Measured silences from detect_silences().
        words: Optional Hammy word list for the no-silence fallback.
        window: How far (seconds) an edge will reach to find a silence.
        safety_margin: Cushion left on the kept side so the cut never lands
            exactly on a voicing onset/offset.

    Returns:
        New list of snapped cut dicts.
    """
    if not cuts:
        return cuts

    # Protected spans = spoken words + vocalization events: the snap-path clamp
    # keeps BOTH whole (an event with interior silence could otherwise be snapped
    # into and clipped). Speech-only `_word_spans` stays for the onset grid below.
    spans = _protected_spans(words or [])
    word_starts = sorted(w["start"] for w in (words or []) if "start" in w)
    word_ends = sorted(w["end"] for w in (words or []) if "end" in w)

    snapped: list[dict] = []
    for cut in cuts:
        s = float(cut["start"])
        e = float(cut["end"])

        sil_e = nearest_silence(e, silences, window)
        if sil_e is not None:
            e = sil_e.end - safety_margin
        elif word_starts:
            nxt = next((ws for ws in word_starts if ws >= e), None)
            if nxt is not None and abs(nxt - e) <= window:
                e = nxt - safety_margin

        sil_s = nearest_silence(s, silences, window)
        if sil_s is not None:
            s = sil_s.start + safety_margin
        elif word_ends:
            prev = next((we for we in reversed(word_ends) if we <= s), None)
            if prev is not None and abs(s - prev) <= window:
                s = prev + safety_margin

        # GLOBAL word-clip safety. A measured silence can reach INTO a word when
        # a soft consonant onset/tail (s/sh/f/th/h) drops below the -25 dB floor
        # and reads as quiet; the snap above would then land an edge strictly
        # inside that word and clip it ("see" -> "ee"). Pull any edge that landed
        # inside a word back to the word's boundary so the word is kept whole. An
        # edge that snapped onto genuine INTER-word quiet is inside no word, so it
        # is left exactly where it landed -- the legitimate audio-first snap is
        # unchanged. Shares _clamp_out_of_words with the micro-cut path so the
        # guarantee holds at every level.
        if spans:
            safe = _clamp_out_of_words(s, e, spans, safety_margin)
            if safe is not None:
                s, e = safe
            else:
                # The pair-clamp found no clean placement -- the safety margin
                # would push an edge into a butt-joined neighbour, or aligned
                # words overlap. Do NOT revert to the caller's raw edges: on the
                # AUTO path those are coarse LLM keep-marks that are themselves
                # mid-word, so reverting would re-clip. Instead snap each edge
                # that sits inside a word to that word's BOUNDARY (no margin, so
                # it can't push into a neighbour), keeping any already-safe edge.
                # A word boundary is not strictly inside a word, so this is
                # word-safe for every case except (vanishingly rare) overlapping
                # forced-aligned words.
                cw = _containing_word(s, spans)
                if cw is not None:
                    s = cw[1]  # leading edge -> word END (keeps the word)
                cw = _containing_word(e, spans)
                if cw is not None:
                    e = cw[0]  # trailing edge -> word START (keeps the word)

        new = dict(cut)
        if s < e:
            new["start"], new["end"] = s, e
        snapped.append(new)

    # Onset tightening (layered on top, never a rewrite of the word-safety above):
    # pull each word-safe edge onto the bordering word's measured onset/offset so
    # the kept audio resumes ON the voice with no leading dead air and no clipped
    # first phoneme. Edges only move to word BOUNDARIES, so the "never inside a
    # spoken word" guarantee is preserved. No-op without `words`.
    return refine_onsets(snapped, words)


# ── Onset refinement (the resume lands ON the voice) ──────────────────────────
# Word-safety (above) keeps a cut edge OUT of any spoken word, but it does not
# decide WHERE in the surrounding quiet the edge sits. A cut end can legitimately
# land anywhere inside the inter-word silence and still be "word-safe" -- yet if
# it lands at the silence's far edge there is a sliver of dead air before the
# next word, so the kept material resumes a beat LATE (Ashley: "doesn't auto snap
# to the beginning of the sound"). Symmetrically a leading edge sitting early in
# the trailing quiet keeps dead air on the outgoing side.
#
# This pass TIGHTENS each already-safe edge onto the measured onset/offset of the
# bordering word: the cut END (the resume point) moves to the START of the next
# kept word; the cut START (the outgoing point) moves to the END of the previous
# kept word. The forced-aligned word START is the audible onset, so landing the
# resume exactly there is a crisp entry with no leading dead air and no clipped
# first phoneme. It is layered ON TOP of the word-safety guarantee, never a
# rewrite of it: an edge only ever moves to a word BOUNDARY (start/end), which is
# by definition NOT strictly inside a word, so the "never inside a spoken word"
# invariant is preserved by construction. Shared by every path (auto snap, the
# export clamp, the serve guard) so what the editor draws and what exports agree.


def _refine_edge_to_onset(
    s: float,
    e: float,
    starts: list[tuple[float, float]],
    ends: list[tuple[float, float]],
    spans: list[tuple[float, float]],
    window: float,
) -> tuple[float, float]:
    """Tighten one cut ``[s, e]`` onto the bordering word onset/offset.

    * ``e`` (resume) -> the START of the nearest kept word at or after ``e``,
      when that word starts within ``window`` and the move stays word-safe and
      leaves a non-empty cut. Kills the dead-air gap before the next word.
    * ``s`` (outgoing) -> the END of the nearest kept word at or before ``s``,
      under the mirror conditions. Trims dead air off the outgoing tail.

    ``starts``/``ends`` are ``(start, end)`` word spans pre-sorted by start and by
    end respectively. Moving an edge to a word boundary can never put it strictly
    inside a word, so this composes with the word-clip guard without weakening it;
    the ``_inside_word`` re-check is a cheap backstop against overlapping aligned
    words. An edge with no word within ``window`` is left exactly where it was.
    """
    # Trailing edge -> next word START (the audible onset of the resume). After
    # the word-clip guard, `e` is never strictly inside a word, so the only move
    # is FORWARD: close a dead-air sliver between `e` and the next word's onset.
    for ws, _we in starts:
        if ws < e:
            continue  # word starts before the resume; skip to the next one
        if ws - e > window:
            break  # sorted by start: no nearer word remains
        # ws is the nearest onset at/after e. Land exactly on it (the crisp
        # entry), unless that boundary is itself inside an overlapping aligned
        # word (backstop). ws > e > s, so the cut stays non-empty.
        if ws > e and not _inside_word(ws, spans):
            e = ws
        break

    # Leading edge -> previous word END (just past the outgoing tail). Mirror:
    # `s` is never inside a word post-guard, so the only move is BACKWARD onto the
    # previous word's offset, trimming dead air kept on the outgoing side.
    for _ws, we in reversed(ends):
        if we > s:
            continue  # word ends after the outgoing point; scan earlier
        if s - we > window:
            break  # sorted by end: no nearer word remains
        # we is the nearest offset at/before s. Pull s back onto it (we < s < e
        # keeps the cut non-empty), unless that boundary is inside an overlapping
        # aligned word (backstop).
        if we < s and not _inside_word(we, spans):
            s = we
        break

    return s, e


def refine_onsets(
    cuts: list[dict],
    words: list[dict] | None,
    window: float = 0.12,
) -> list[dict]:
    """Snap each already-word-safe cut so the kept audio resumes ON the voice.

    A tightening pass run AFTER ``snap_cuts_to_silence`` / the export word-clamp:
    it moves the cut END onto the next kept word's measured onset and the cut
    START onto the previous kept word's offset, so there is no leading dead air at
    the resume and no clipped first phoneme. Edges only move to word BOUNDARIES,
    so the global "never strictly inside a spoken word" guarantee is preserved.
    Returns a new list; non-edge keys are kept. A no-op without ``words``.

    Args:
        cuts: ``{start, end, ...}`` removed spans (word-safe edges expected).
        words: Hammy word list; event tokens are excluded from the onset grid.
        window: How far (seconds) an edge reaches to find a bordering word. Kept
            tight (120 ms) so it only closes a real dead-air sliver, never hops to
            a distant word and eats kept content.
    """
    if not cuts or not words:
        return cuts
    spans = _word_spans(words)
    if not spans:
        return cuts
    starts = spans  # already sorted by start
    ends = sorted(spans, key=lambda sp: sp[1])

    out: list[dict] = []
    for cut in cuts:
        s = float(cut["start"])
        e = float(cut["end"])
        ns, ne = _refine_edge_to_onset(s, e, starts, ends, spans, window)
        new = dict(cut)
        if ne > ns:  # only adopt a non-empty tightening
            new["start"], new["end"] = ns, ne
        out.append(new)
    return out


def edge_lands_in_silence(t: float, silences: list[Silence]) -> bool:
    """True if time `t` falls inside any measured silence (a clean cut point)."""
    return any(s.contains(t) for s in silences)


def silences_to_pairs(silences: list[Silence]) -> list[list[float]]:
    """Serialize for caching: [[start, end], ...]."""
    return [[s.start, s.end] for s in silences]


def silences_from_pairs(pairs: list[list[float]]) -> list[Silence]:
    """Inverse of silences_to_pairs."""
    return [Silence(float(a), float(b)) for a, b in pairs]
