# GENERATED by studio/tools/sync-engine.sh from clipforge/clipforge/filler.py.
# Do not edit it: change the source and run the script. `sync-engine.sh --check` fails on drift.
"""
Filler word detection and removal.

Scans word-level timestamps for filler words (um, uh, like, you know)
and dead gaps between words. Three aggression levels control what gets cut.

Levels:
  0 — no filler removal
  1 — light: only um, uh, er, ah
  2 — medium: adds like, you know, I mean, so, right, basically, literally
  3 — aggressive: medium + repeated words + pauses > 0.4s
"""

from dataclasses import dataclass
from pathlib import Path

# The um/uh hesitation family — always fillers, never content words. Widened
# with the common transcript spellings (uhm, mm/mmm, mhm, huh, eh) so light
# removal stops missing them. "like" et al. stay out of light (level 1) and
# only join at medium (level 2).
_LIGHT_FILLERS = {
    "um", "uh", "er", "ah", "umm", "uhh", "hmm",
    "uhm", "mm", "mmm", "mhm", "huh", "eh",
}

_MEDIUM_FILLERS = _LIGHT_FILLERS | {
    "like", "you know", "i mean", "so", "right",
    "basically", "literally", "actually", "honestly",
    "kind of", "sort of",
}

_PAUSE_THRESHOLD = 0.4


@dataclass
class FillerSegment:
    start: float
    end: float
    reason: str

    @property
    def duration(self) -> float:
        return self.end - self.start


def detect_fillers(
    words: list[dict],
    level: int = 1,
    clip_start: float = 0.0,
    clip_end: float | None = None,
) -> list[FillerSegment]:
    """Detect filler words and dead gaps in a word-timestamp list.

    Args:
        words: List of {"word": str, "start": float, "end": float}.
        level: Aggression level 0-3.
        clip_start: Only consider words after this time.
        clip_end: Only consider words before this time.

    Returns:
        Sorted list of FillerSegment to remove.
    """
    if level == 0:
        return []

    fillers_set = _LIGHT_FILLERS if level == 1 else _MEDIUM_FILLERS

    clip_words = [
        w for w in words
        if w["start"] >= clip_start
        and (clip_end is None or w["end"] <= clip_end)
    ]

    if not clip_words:
        return []

    segments: list[FillerSegment] = []

    # Single-word fillers
    for w in clip_words:
        clean = w["word"].strip().lower().rstrip(".,!?")
        if clean in fillers_set:
            segments.append(FillerSegment(
                start=w["start"],
                end=w["end"],
                reason=f"filler: {clean}",
            ))

    # Multi-word fillers (bigrams)
    if level >= 2:
        bigram_fillers = {"you know", "i mean", "kind of", "sort of"}
        for i in range(len(clip_words) - 1):
            bigram = (
                clip_words[i]["word"].strip().lower().rstrip(".,!?")
                + " "
                + clip_words[i + 1]["word"].strip().lower().rstrip(".,!?")
            )
            if bigram in bigram_fillers:
                segments.append(FillerSegment(
                    start=clip_words[i]["start"],
                    end=clip_words[i + 1]["end"],
                    reason=f"filler: {bigram}",
                ))

    # Repeated words (stutters): "I I I", "the the"
    if level >= 3:
        for i in range(len(clip_words) - 1):
            w1 = clip_words[i]["word"].strip().lower().rstrip(".,!?")
            w2 = clip_words[i + 1]["word"].strip().lower().rstrip(".,!?")
            if w1 == w2 and len(w1) > 1:
                segments.append(FillerSegment(
                    start=clip_words[i]["start"],
                    end=clip_words[i]["end"],
                    reason=f"repeat: {w1}",
                ))

    # Dead gaps
    if level >= 3:
        for i in range(len(clip_words) - 1):
            gap_start = clip_words[i]["end"]
            gap_end = clip_words[i + 1]["start"]
            gap = gap_end - gap_start
            if gap > _PAUSE_THRESHOLD:
                segments.append(FillerSegment(
                    start=gap_start,
                    end=gap_end,
                    reason=f"pause: {gap:.1f}s",
                ))

    # Merge overlapping segments and sort
    segments.sort(key=lambda s: s.start)
    return _merge_overlapping(segments)


def _merge_overlapping(segments: list[FillerSegment]) -> list[FillerSegment]:
    """Merge overlapping or adjacent filler segments."""
    if not segments:
        return []

    merged: list[FillerSegment] = [segments[0]]
    for seg in segments[1:]:
        prev = merged[-1]
        if seg.start <= prev.end + 0.05:
            merged[-1] = FillerSegment(
                start=prev.start,
                end=max(prev.end, seg.end),
                reason=f"{prev.reason}; {seg.reason}",
            )
        else:
            merged.append(seg)

    return merged


def compute_keep_segments(
    clip_start: float,
    clip_end: float,
    fillers: list[FillerSegment],
    min_segment: float = 0.1,
) -> list[tuple[float, float]]:
    """Compute the segments to keep after removing fillers.

    Returns list of (start, end) time ranges relative to clip_start=0.
    """
    if not fillers:
        return [(0.0, clip_end - clip_start)]

    keeps: list[tuple[float, float]] = []
    cursor = clip_start

    for filler in fillers:
        if filler.start > cursor + min_segment:
            keeps.append((cursor - clip_start, filler.start - clip_start))
        cursor = max(cursor, filler.end)

    if clip_end > cursor + min_segment:
        keeps.append((cursor - clip_start, clip_end - clip_start))

    return keeps


def remove_fillers(
    video_path: Path,
    keep_segments: list[tuple[float, float]],
    output_path: Path,
) -> Path:
    """Remove filler segments from a video using ffmpeg concat filter.

    Args:
        video_path: Source clip.
        keep_segments: List of (start, end) time ranges to keep (clip-relative).
        output_path: Where to write the cleaned clip.

    Returns:
        Path to the cleaned clip, or original if removal fails/no-op.
    """
    import subprocess

    if not keep_segments or len(keep_segments) < 2:
        return video_path

    output_path.parent.mkdir(parents=True, exist_ok=True)

    # Build filter_complex: split into segments, then concat
    n = len(keep_segments)
    filter_parts: list[str] = []
    stream_labels: list[str] = []

    for i, (start, end) in enumerate(keep_segments):
        vl = f"[v{i}]"
        al = f"[a{i}]"
        filter_parts.append(
            f"[0:v]trim=start={start:.3f}:end={end:.3f},setpts=PTS-STARTPTS{vl};"
            f"[0:a]atrim=start={start:.3f}:end={end:.3f},asetpts=PTS-STARTPTS{al}"
        )
        stream_labels.append(f"{vl}{al}")

    concat_inputs = "".join(stream_labels)
    filter_parts.append(
        f"{concat_inputs}concat=n={n}:v=1:a=1[outv][outa]"
    )
    filter_complex = ";".join(filter_parts)

    cmd = [
        "ffmpeg", "-y",
        "-i", str(video_path),
        "-filter_complex", filter_complex,
        "-map", "[outv]", "-map", "[outa]",
        "-c:v", "libx264", "-preset", "fast", "-crf", "23",
        "-c:a", "copy",
        str(output_path),
    ]

    result = subprocess.run(cmd, capture_output=True, text=True, timeout=600)
    if result.returncode != 0:
        # Audio copy might fail with concat; retry with re-encode
        cmd_retry = [
            "ffmpeg", "-y",
            "-i", str(video_path),
            "-filter_complex", filter_complex,
            "-map", "[outv]", "-map", "[outa]",
            "-c:v", "libx264", "-preset", "fast", "-crf", "23",
            "-c:a", "aac", "-b:a", "256k",
            str(output_path),
        ]
        result = subprocess.run(cmd_retry, capture_output=True, text=True, timeout=600)

    if result.returncode != 0 or not output_path.exists():
        print(f"[clipforge] Filler removal failed: {result.stderr[-200:]}")
        return video_path

    return output_path


def filler_summary(fillers: list[FillerSegment]) -> str:
    """One-line summary of what would be cut."""
    if not fillers:
        return "no fillers detected"
    total = sum(f.duration for f in fillers)
    return f"{len(fillers)} fillers ({total:.1f}s total)"
