# GENERATED by studio/tools/sync-engine.sh from clipforge/clipforge/longform.py.
# Do not edit it: change the source and run the script. `sync-engine.sh --check` fails on drift.
"""
Longform video editor — removes dead air, filler words, and stutters
to tighten pacing while preserving original quality and aspect ratio.

Five aggression levels control how aggressively gaps are cut:
  1 — Very Subtle: only obvious dead air (2s+ pauses)
  2 — Subtle: noticeable pauses (1s+)
  3 — Medium: pauses + basic filler words
  4 — High: shorter pauses + more fillers + repeated words
  5 — Cut for Time: maximum aggression, shortest pauses
"""

from __future__ import annotations

import subprocess
from dataclasses import dataclass
from pathlib import Path


@dataclass
class EditLevel:
    name: str
    pause_threshold: float
    filler_words: frozenset[str]
    bigram_fillers: frozenset[str]
    cut_repeats: bool
    min_keep_gap: float
    crossfade_ms: int
    min_segment: float = 3.0
    context_gap: float = 0.15


# The "um/uh" family: non-lexical hesitation sounds that are always fillers,
# never content words, so they're cut unconditionally (no pause-context guard).
# Single source of truth — every level that cuts fillers composes from this set,
# which structurally guarantees the monotonic-superset order across levels.
# Widened beyond the old um/uh/er/ah core with the common spellings real
# transcripts produce (uhm, mm/mmm, mhm, huh, eh) so they stop slipping through
# at the default (Medium) level.
_CORE_FILLERS = frozenset({
    "um", "uh", "er", "ah", "umm", "uhh", "hmm",
    "uhm", "mm", "mmm", "mhm", "huh", "eh",
})


# Crutch conjunctions/hedges Ashley over-uses ("and", "like"). Unlike
# _CORE_FILLERS these are REAL lexical words that are usually load-bearing, so at
# the DEFAULT level they are cut ONLY as crutch fillers: the CONTEXT_FILLERS
# pause-context guard below requires an adjacent pause (or a doubled "and and" /
# "like like") before one is removed, and never touches one wedged between two
# words with no pause. Levels 4-5 already carry these (plus more) in their own
# filler sets, so this only extends the default level — the monotonic superset
# order across levels is preserved.
_DEFAULT_CRUTCH_FILLERS = frozenset({"and", "like"})


EDIT_LEVELS: dict[int, EditLevel] = {
    1: EditLevel(
        name="Very Subtle",
        pause_threshold=2.0,
        filler_words=frozenset(),
        bigram_fillers=frozenset(),
        cut_repeats=False,
        min_keep_gap=0.3,
        crossfade_ms=40,
    ),
    2: EditLevel(
        name="Subtle",
        pause_threshold=1.0,
        filler_words=frozenset(),
        bigram_fillers=frozenset(),
        cut_repeats=False,
        min_keep_gap=0.2,
        crossfade_ms=40,
    ),
    3: EditLevel(
        name="Medium",
        # Default level. Retuned less conservative: 0.6 -> 0.5s catches more of
        # the genuine dead-air that slipped through, while staying above level 2
        # (1.0s) and below level 4 (0.35s). Fillers = the full um/uh family plus
        # the crutch "and"/"like" (cut only when pause-adjacent — see the
        # CONTEXT_FILLERS guard in detect_edit_cuts).
        pause_threshold=0.5,
        filler_words=_CORE_FILLERS | _DEFAULT_CRUTCH_FILLERS,
        bigram_fillers=frozenset(),
        cut_repeats=False,
        min_keep_gap=0.15,
        crossfade_ms=35,
    ),
    4: EditLevel(
        name="High",
        pause_threshold=0.35,
        filler_words=_CORE_FILLERS | frozenset({
            "like", "so", "right", "and", "basically", "literally",
            "actually", "honestly",
        }),
        bigram_fillers=frozenset({"you know", "i mean"}),
        cut_repeats=True,
        min_keep_gap=0.1,
        crossfade_ms=30,
        min_segment=2.0,
    ),
    5: EditLevel(
        name="Cut for Time",
        pause_threshold=0.15,
        filler_words=_CORE_FILLERS | frozenset({
            "like", "so", "right", "and", "well", "basically", "literally",
            "actually", "honestly", "just", "okay",
        }),
        bigram_fillers=frozenset({"you know", "i mean", "kind of", "sort of"}),
        cut_repeats=True,
        min_keep_gap=0.03,
        crossfade_ms=25,
        min_segment=1.0,
        context_gap=0.08,
    ),
}


@dataclass
class EditCut:
    start: float
    end: float
    reason: str

    @property
    def duration(self) -> float:
        return self.end - self.start


def snap_user_cuts_to_gaps(
    cuts: list[dict],
    words: list[dict],
    min_gap: float = 0.05,
    safety_margin: float = 0.005,
) -> list[dict]:
    """Push user-marked cut endpoints into the silent gaps around them.

    The browser editor's cuts are aligned to word.start / word.end as reported
    by the transcription model, which has ±50–200 ms wobble. That wobble bleeds
    a fraction of the cut word's acoustics into the kept side. When a real
    silent gap exists between the cut span and the neighbouring kept words,
    we extend the cut INTO that gap (leaving a small safety margin) so the
    boundary lands in silence instead of mid-phoneme.

    No-op when there is no gap (back-to-back speech) — we never eat into a
    kept word. Speech-event tokens (type='event') are treated like words.

    Args:
        cuts: List of {start, end} dicts in source-time seconds.
        words: Full word-timestamp list from the transcription.
        min_gap: Only snap when the surrounding gap is at least this large
            (seconds). Smaller gaps probably aren't real silence.
        safety_margin: Pull back this far from the next word's start (and
            push forward this far from the prev word's end) so the cut
            doesn't land exactly on a voicing onset.

    Returns:
        New list of snapped {start, end, ...} dicts (any extra keys preserved).
    """
    if not cuts or not words:
        return cuts

    # Sort the speech-and-event tokens by start time once.
    ws = sorted(
        (w for w in words if "start" in w and "end" in w),
        key=lambda w: w["start"],
    )
    if not ws:
        return cuts

    starts = [w["start"] for w in ws]
    ends = [w["end"] for w in ws]

    def _first_word_at_or_after(t: float) -> int | None:
        # Bisect-right on starts: first index where start >= t.
        lo, hi = 0, len(starts)
        while lo < hi:
            mid = (lo + hi) // 2
            if starts[mid] < t:
                lo = mid + 1
            else:
                hi = mid
        return lo if lo < len(starts) else None

    snapped: list[dict] = []
    for cut in cuts:
        s = float(cut["start"])
        e = float(cut["end"])

        # ── Extend the trailing edge into a silent gap ──────────────
        idx_next = _first_word_at_or_after(e)
        if idx_next is not None:
            gap = starts[idx_next] - e
            if gap >= min_gap:
                e = starts[idx_next] - safety_margin

        # ── Extend the leading edge backward into a silent gap ─────
        # Find last word ending at-or-before s.
        idx_prev = None
        for i in range(len(ends) - 1, -1, -1):
            if ends[i] <= s:
                idx_prev = i
                break
        if idx_prev is not None:
            gap = s - ends[idx_prev]
            if gap >= min_gap:
                s = ends[idx_prev] + safety_margin

        # Preserve any extra keys (e.g. 'reason').
        new = dict(cut)
        new["start"] = s
        new["end"] = e
        snapped.append(new)

    return snapped


def pad_keep_ranges_into_gaps(
    ranges: list[tuple[float, float]],
    words: list[dict],
    lead_pad: float = 0.15,
    tail_pad: float = 0.35,
    safety_margin: float = 0.02,
) -> list[tuple[float, float]]:
    """Give keep-ranges breathing room by extending them into surrounding silence.

    The inverse of snap_user_cuts_to_gaps: that function operates on REMOVED
    spans, this one operates on KEPT spans (shortform clip ranges). A range
    that ends exactly at word.end clips the final phoneme and feels abrupt;
    extending the tail into the following silent gap lets the word land.

    Each range start is pulled back up to lead_pad seconds and each end is
    pushed forward up to tail_pad seconds, but never past the neighbouring
    word (minus safety_margin) — we don't pull fragments of adjacent speech
    into the clip.

    Args:
        ranges: List of (start, end) keep spans in source-time seconds.
        words: Full word-timestamp list from the transcription.
        lead_pad: Max seconds to extend the start backward.
        tail_pad: Max seconds to extend the end forward.
        safety_margin: Keep this far from neighbouring words.

    Returns:
        New list of (start, end) tuples.
    """
    if not ranges or not words:
        return ranges

    ws = sorted(
        (w for w in words if "start" in w and "end" in w),
        key=lambda w: w["start"],
    )
    if not ws:
        return ranges

    starts = [w["start"] for w in ws]
    ends = [w["end"] for w in ws]

    padded: list[tuple[float, float]] = []
    for s, e in ranges:
        # ── Tail: push end into the following gap ──────────────────
        next_start = None
        for t in starts:
            if t >= e:
                next_start = t
                break
        limit = (next_start - safety_margin) if next_start is not None else e + tail_pad
        new_e = min(e + tail_pad, max(e, limit))

        # ── Lead: pull start back into the preceding gap ───────────
        prev_end = None
        for t in reversed(ends):
            if t <= s:
                prev_end = t
                break
        limit = (prev_end + safety_margin) if prev_end is not None else s - lead_pad
        new_s = max(s - lead_pad, min(s, limit), 0.0)

        padded.append((new_s, new_e))

    return padded


def detect_intra_segment_cuts(
    range_start: float,
    range_end: float,
    words: list[dict],
    max_gap: float = 0.25,
    keep: float = 0.15,
    tail_guard: float = 0.5,
) -> list[dict]:
    """Detect silent gaps within a kept segment for jump-cut removal.

    Walks consecutive word pairs inside [range_start, range_end] and emits a
    cut span wherever the inter-word gap exceeds max_gap and contains no event
    token. Each cut leaves keep/2 of natural pause on each side so the edit
    doesn't feel mechanical. Gaps in the final tail_guard seconds are skipped
    to avoid cutting into padded breathing room.

    Args:
        range_start: Clip start in source seconds.
        range_end: Clip end in source seconds.
        words: Full word-timestamp list (including event tokens).
        max_gap: Minimum inter-word silence to cut (seconds).
        keep: Total silence to preserve across each cut (keep/2 on each side).
        tail_guard: Skip gaps starting in the last N seconds of the range.

    Returns:
        List of {start, end} dicts in source time suitable for clip_def["cuts"].
    """
    ws = sorted(
        (w for w in words if "start" in w and "end" in w),
        key=lambda w: w["start"],
    )
    # Filter to words/events inside the range.
    in_range = [w for w in ws if w["end"] > range_start and w["start"] < range_end]
    if len(in_range) < 2:
        return []

    cuts: list[dict] = []
    tail_cutoff = range_end - tail_guard

    for prev, nxt in zip(in_range, in_range[1:]):
        gap_start = prev["end"]
        gap_end = nxt["start"]
        gap = gap_end - gap_start
        if gap <= max_gap:
            continue
        # Skip gaps in the tail-guard zone.
        if gap_start >= tail_cutoff:
            continue
        # Skip if any event token occupies this gap.
        event_in_gap = any(
            w.get("type") == "event"
            and w["start"] < gap_end
            and w["end"] > gap_start
            for w in ws
        )
        if event_in_gap:
            continue
        half = keep / 2.0
        cut_s = gap_start + half
        cut_e = gap_end - half
        if cut_e <= cut_s:
            continue
        # Clamp to range boundaries (should never fire, defensive).
        cut_s = max(cut_s, range_start)
        cut_e = min(cut_e, range_end)
        cuts.append({"start": cut_s, "end": cut_e})

    return cuts


def _has_vocalization(words: list[dict], gap_start: float, gap_end: float) -> bool:
    """Check if a gap contains a voiced vocalization event from Hammy."""
    for w in words:
        if w.get("type") != "event":
            continue
        if w["start"] >= gap_start and w["end"] <= gap_end:
            return True
        if w["start"] < gap_end and w["end"] > gap_start:
            return True
    return False


def _adjacent_to_vocalization(
    words: list[dict], start: float, end: float, margin: float = 0.1,
) -> bool:
    """Check if a time range is directly adjacent to a vocalization event."""
    for w in words:
        if w.get("type") != "event":
            continue
        if abs(w["end"] - start) <= margin or abs(w["start"] - end) <= margin:
            return True
        if w["start"] < end and w["end"] > start:
            return True
    return False


def detect_edit_cuts(
    words: list[dict],
    level: int = 3,
) -> list[EditCut]:
    """Detect segments to cut based on aggression level.

    Voiced vocalizations (laughter, moans, gasps) are always protected.
    """
    if level not in EDIT_LEVELS:
        level = 3
    edit_level = EDIT_LEVELS[level]

    speech_words = [w for w in words if w.get("type") != "event"]
    if not speech_words:
        return []

    cuts: list[EditCut] = []

    # Pause detection
    SENTENCE_END_MULTIPLIER = 1.8
    for i in range(1, len(speech_words)):
        gap_start = speech_words[i - 1]["end"]
        gap_end = speech_words[i]["start"]
        gap_dur = gap_end - gap_start

        threshold = edit_level.pause_threshold
        prev_text = speech_words[i - 1]["word"].strip()
        if prev_text and prev_text[-1] in ".?!":
            threshold *= SENTENCE_END_MULTIPLIER

        if gap_dur < threshold:
            continue

        if _has_vocalization(words, gap_start, gap_end):
            continue

        keep = edit_level.min_keep_gap
        cut_start = gap_start + keep / 2
        cut_end = gap_end - keep / 2
        if cut_end <= cut_start:
            continue

        cuts.append(EditCut(
            start=cut_start,
            end=cut_end,
            reason=f"pause: {gap_dur:.1f}s",
        ))

    # Filler word detection (context-aware)
    # Words like "so", "like", "right" are only fillers when standalone —
    # preceded or followed by a pause, not tightly bound in flowing speech.
    # Words adjacent to vocalizations are always protected.
    CONTEXT_FILLERS = frozenset({
        "like", "so", "right", "and", "well", "basically", "literally",
        "actually", "honestly", "just", "okay",
    })
    context_gap = edit_level.context_gap
    if edit_level.filler_words:
        for idx, w in enumerate(speech_words):
            clean = w["word"].strip().lower().rstrip(".,!?")
            if clean not in edit_level.filler_words:
                continue

            if clean in CONTEXT_FILLERS:
                if _adjacent_to_vocalization(words, w["start"], w["end"]):
                    continue
                # A doubled crutch ("and and" / "like like") is a stutter-crutch
                # even with no surrounding pause: cut the FIRST of the pair (the
                # duplicate) and leave the second to stand or fall on its own
                # pause context — mirrors the level 4/5 repeat detector.
                next_clean = (
                    speech_words[idx + 1]["word"].strip().lower().rstrip(".,!?")
                    if idx < len(speech_words) - 1 else ""
                )
                doubled = bool(next_clean) and next_clean == clean
                if not doubled:
                    gap_before = (
                        w["start"] - speech_words[idx - 1]["end"]
                        if idx > 0 else float("inf")
                    )
                    gap_after = (
                        speech_words[idx + 1]["start"] - w["end"]
                        if idx < len(speech_words) - 1 else float("inf")
                    )
                    # Load-bearing: wedged between two words with no pause on
                    # either side — keep it. Cut only when a pause is adjacent.
                    if gap_before < context_gap and gap_after < context_gap:
                        continue

            cuts.append(EditCut(
                start=w["start"],
                end=w["end"],
                reason=f"filler: {clean}",
            ))

    # Bigram filler detection
    if edit_level.bigram_fillers:
        for i in range(len(speech_words) - 1):
            bigram = (
                speech_words[i]["word"].strip().lower().rstrip(".,!?")
                + " "
                + speech_words[i + 1]["word"].strip().lower().rstrip(".,!?")
            )
            if bigram in edit_level.bigram_fillers:
                cuts.append(EditCut(
                    start=speech_words[i]["start"],
                    end=speech_words[i + 1]["end"],
                    reason=f"filler: {bigram}",
                ))

    # Repeated word detection (stutters)
    if edit_level.cut_repeats:
        for i in range(len(speech_words) - 1):
            w1 = speech_words[i]["word"].strip().lower().rstrip(".,!?")
            w2 = speech_words[i + 1]["word"].strip().lower().rstrip(".,!?")
            if w1 == w2 and len(w1) > 1:
                cuts.append(EditCut(
                    start=speech_words[i]["start"],
                    end=speech_words[i]["end"],
                    reason=f"repeat: {w1}",
                ))

    cuts.sort(key=lambda c: c.start)
    merged = _merge_overlapping(cuts)
    buffered = _apply_vocalization_lead_in(merged, words)
    meaningful = [c for c in buffered if c.duration >= MIN_CUT_SECONDS]
    return _enforce_min_segment(meaningful, speech_words, edit_level.min_segment)


VOCALIZATION_LEAD_IN = 0.3
MIN_CUT_SECONDS = 0.2


def _apply_vocalization_lead_in(
    cuts: list[EditCut], words: list[dict],
) -> list[EditCut]:
    """Pull back cut endpoints that land right before a vocalization.

    Snaps adjusted boundaries to word edges so cuts never land mid-word.
    """
    events = [w for w in words if w.get("type") == "event"]
    if not events:
        return cuts

    all_words = [w for w in words if w.get("type") != "event"]

    def _snap_end_to_word_boundary(t: float) -> float:
        for w in all_words:
            if w["start"] < t < w["end"]:
                return w["start"]
        return t

    def _snap_start_to_word_boundary(t: float) -> float:
        for w in all_words:
            if w["start"] < t < w["end"]:
                return w["end"]
        return t

    result = []
    for cut in cuts:
        new_end = cut.end
        for ev in events:
            gap = ev["start"] - cut.end
            if 0.05 <= gap <= VOCALIZATION_LEAD_IN:
                new_end = min(new_end, ev["start"] - VOCALIZATION_LEAD_IN)
        new_end = _snap_end_to_word_boundary(new_end)

        new_start = cut.start
        for ev in events:
            gap = cut.start - ev["end"]
            if 0.05 <= gap <= VOCALIZATION_LEAD_IN:
                new_start = max(new_start, ev["end"] + VOCALIZATION_LEAD_IN)
        new_start = _snap_start_to_word_boundary(new_start)

        if new_end > new_start:
            result.append(EditCut(new_start, new_end, cut.reason))
        else:
            result.append(cut)
    return result
MIN_SEGMENT_SECONDS = 3.0


def _enforce_min_segment(
    cuts: list[EditCut],
    speech_words: list[dict],
    min_segment: float = MIN_SEGMENT_SECONDS,
) -> list[EditCut]:
    """Drop cuts that would create keep segments shorter than MIN_SEGMENT_SECONDS.

    When two cuts are too close together, drops the smaller one (preserving
    more content) rather than merging them into one large cut.
    """
    if not cuts or not speech_words:
        return cuts

    timeline_start = speech_words[0]["start"]
    timeline_end = speech_words[-1]["end"]
    total_dur = timeline_end - timeline_start

    if total_dur < min_segment * 3:
        return cuts

    cuts = list(cuts)

    while True:
        worst_dur = float("inf")
        worst_pos = -1

        for i in range(1, len(cuts)):
            seg_dur = cuts[i].start - cuts[i - 1].end
            if seg_dur < min_segment and seg_dur < worst_dur:
                worst_dur = seg_dur
                worst_pos = i

        if cuts:
            trailing = timeline_end - cuts[-1].end
            if trailing < min_segment and trailing < worst_dur:
                cuts.pop()
                continue

        if worst_pos < 0:
            break

        left = worst_pos - 1
        right = worst_pos
        if cuts[left].duration <= cuts[right].duration:
            cuts.pop(left)
        else:
            cuts.pop(right)

    return cuts


def _merge_overlapping(cuts: list[EditCut]) -> list[EditCut]:
    if not cuts:
        return []
    merged: list[EditCut] = [cuts[0]]
    for cut in cuts[1:]:
        prev = merged[-1]
        if cut.start <= prev.end + 0.05:
            merged[-1] = EditCut(
                start=prev.start,
                end=max(prev.end, cut.end),
                reason=f"{prev.reason}; {cut.reason}",
            )
        else:
            merged.append(cut)
    return merged


def snap_to_sentence_boundary(
    cuts: list[EditCut],
    words: list[dict],
    snap_window: float = 0.5,
) -> list[EditCut]:
    """Shift cut boundaries to align with sentence-ending punctuation."""
    speech_words = [w for w in words if w.get("type") != "event"]
    if not speech_words:
        return cuts

    sentence_ends: list[tuple[float, int]] = []
    for i, w in enumerate(speech_words):
        text = w["word"].strip()
        if text and text[-1] in ".?!;":
            sentence_ends.append((w["end"], i))

    snapped: list[EditCut] = []
    for cut in cuts:
        best_start = cut.start
        best_end = cut.end

        for se_time, se_idx in sentence_ends:
            if abs(se_time - cut.start) < snap_window and se_time <= cut.end:
                best_start = se_time
                break

        for se_time, se_idx in sentence_ends:
            if abs(se_time - cut.end) < snap_window and se_time >= cut.start:
                if se_idx + 1 < len(speech_words):
                    candidate = speech_words[se_idx + 1]["start"]
                    if candidate <= cut.end + snap_window:
                        best_end = candidate

        if best_end - best_start > cut.duration * 1.5:
            snapped.append(cut)
        elif best_end > best_start:
            snapped.append(EditCut(
                start=best_start,
                end=best_end,
                reason=cut.reason,
            ))
        else:
            snapped.append(cut)

    return snapped


def compute_keep_segments(
    video_duration: float,
    cuts: list[EditCut],
) -> list[tuple[float, float]]:
    """Convert cuts into absolute-timestamp keep segments."""
    if not cuts:
        return [(0.0, video_duration)]

    keeps: list[tuple[float, float]] = []
    cursor = 0.0

    for cut in cuts:
        if cut.start > cursor + 0.01:
            keeps.append((cursor, cut.start))
        cursor = max(cursor, cut.end)

    if video_duration > cursor + 0.01:
        keeps.append((cursor, video_duration))

    return keeps


def build_edit_filter(
    keep_segments: list[tuple[float, float]],
    crossfade_ms: int = 40,
) -> str:
    """Build ffmpeg filter_complex with audio micro-fades at cut points."""
    if not keep_segments:
        return ""

    n = len(keep_segments)
    fade_sec = crossfade_ms / 1000.0
    filter_parts: list[str] = []
    stream_labels: list[str] = []

    for i, (start, end) in enumerate(keep_segments):
        seg_dur = end - start
        vl = f"[v{i}]"
        al = f"[a{i}]"

        filter_parts.append(
            f"[0:v]trim=start={start:.3f}:end={end:.3f},setpts=PTS-STARTPTS{vl}"
        )

        afade_parts = f"[0:a]atrim=start={start:.3f}:end={end:.3f},asetpts=PTS-STARTPTS"
        if i > 0 and seg_dur > fade_sec:
            afade_parts += f",afade=t=in:d={fade_sec:.3f}"
        if i < n - 1 and seg_dur > fade_sec:
            fade_start = seg_dur - fade_sec
            afade_parts += f",afade=t=out:st={fade_start:.3f}:d={fade_sec:.3f}"
        afade_parts += al

        filter_parts.append(afade_parts)
        stream_labels.append(f"{vl}{al}")

    concat_inputs = "".join(stream_labels)
    filter_parts.append(f"{concat_inputs}concat=n={n}:v=1:a=1[outv][outa]")

    return ";".join(filter_parts)


def get_video_duration(video_path: Path) -> float:
    result = subprocess.run(
        ["ffprobe", "-v", "error", "-show_entries", "format=duration",
         "-of", "default=noprint_wrappers=1:nokey=1", str(video_path)],
        capture_output=True, text=True, timeout=30,
    )
    return float(result.stdout.strip())


def edit_video(
    video_path: Path,
    words: list[dict],
    level: int = 3,
    output_path: Path | None = None,
    config: dict | None = None,
    cuts: list[EditCut] | None = None,
) -> Path:
    """Assemble edited video in a single ffmpeg pass.

    If cuts is provided, uses those directly. Otherwise detects cuts from words.
    """
    from lumr_studio.engine.config import EXPORTS_DIR, ensure_dirs, load_config
    from lumr_studio.engine.editor import _sanitize_dirname, detect_encoder

    if config is None:
        config = load_config()
    ensure_dirs()

    edit_config = config.get("edit", {})
    edit_level = EDIT_LEVELS.get(level, EDIT_LEVELS[3])

    if cuts is None:
        cuts = detect_edit_cuts(words, level)
        cuts = snap_to_sentence_boundary(cuts, words)

    video_duration = get_video_duration(video_path)
    keeps = compute_keep_segments(video_duration, cuts)

    if len(keeps) <= 1 and not cuts:
        print("[clipforge] No cuts detected — video unchanged.")
        return video_path

    if output_path is None:
        safe_stem = _sanitize_dirname(video_path.stem)
        output_dir = EXPORTS_DIR / safe_stem
        output_dir.mkdir(parents=True, exist_ok=True)
        output_path = output_dir / f"{video_path.stem}_edited_L{level}.mp4"

    crossfade_ms = edit_config.get("crossfade_ms", edit_level.crossfade_ms)
    filter_complex = build_edit_filter(keeps, crossfade_ms)

    encoder = detect_encoder(edit_config.get("encoder", "auto"))

    if encoder == "libx264":
        crf = edit_config.get("crf", 18)
        video_args = ["-c:v", "libx264", "-preset", "medium", "-crf", str(crf)]
    else:
        bitrate = edit_config.get("video_bitrate", "8M")
        video_args = ["-c:v", encoder, "-b:v", bitrate]

    audio_bitrate = edit_config.get("audio_bitrate", "256k")

    cmd = [
        "ffmpeg", "-y",
        "-i", str(video_path),
        "-filter_complex", filter_complex,
        "-map", "[outv]", "-map", "[outa]",
        *video_args,
        "-c:a", "aac", "-b:a", audio_bitrate,
        str(output_path),
    ]

    print(f"[clipforge] Assembling edited video ({len(keeps)} segments)...")
    result = subprocess.run(cmd, capture_output=True, text=True, timeout=3600)

    if result.returncode != 0:
        if encoder != "libx264":
            print(f"[clipforge] {encoder} failed, falling back to libx264...")
            crf = edit_config.get("crf", 18)
            cmd_fallback = [
                "ffmpeg", "-y",
                "-i", str(video_path),
                "-filter_complex", filter_complex,
                "-map", "[outv]", "-map", "[outa]",
                "-c:v", "libx264", "-preset", "medium", "-crf", str(crf),
                "-c:a", "aac", "-b:a", audio_bitrate,
                str(output_path),
            ]
            result = subprocess.run(cmd_fallback, capture_output=True, text=True, timeout=3600)

    if result.returncode != 0 or not output_path.exists():
        raise RuntimeError(f"ffmpeg failed: {result.stderr[-500:]}")

    return output_path


def edit_summary(cuts: list[EditCut], video_duration: float) -> str:
    if not cuts:
        return "no cuts detected"
    total_cut = sum(c.duration for c in cuts)
    pct = (total_cut / video_duration * 100) if video_duration > 0 else 0
    mins = int(video_duration // 60)
    secs = int(video_duration % 60)
    return f"{len(cuts)} cuts ({total_cut:.1f}s removed, {pct:.1f}% of {mins}:{secs:02d})"
