# GENERATED by studio/tools/sync-engine.sh from clipforge/clipforge/microcut_pacing.py.
# Do not edit it: change the source and run the script. `sync-engine.sh --check` fails on drift.
"""Micro-cut pacing layer (scope S3).

The within-beat jump-cuts that tighten kept material. ``longform.detect_edit_cuts``
already finds removable spans (pauses, fillers, stutters) from the word list at a
given aggression level. This module is the *pacing* pass on top of it:

  1. keep micro-cuts only inside KEPT material (intersect with the StoryMap's
     non-cut beats, so we never micro-cut a span the model already dropped);
  2. land every micro-cut edge on a real S0 measured silence (audio_boundaries),
     so a cut never clips a word -- the boundaries the editor magnets onto;
  3. hand the inspector a clean, human ``reason`` string ("pause: 2.3s",
     "filler: um", "stutter: the the");
  4. expose a single level/density knob that visibly trades pace for content.

The vocalization protection from ``detect_edit_cuts`` (laughter / moans / gasps,
``type == "event"``) is preserved end-to-end -- this layer only ever *removes*
candidate cuts, it never adds an unprotected one.

Output is the locked ``/api/microcuts`` shape: ``[{start, end, reason}]``. This
module does not change that shape; it produces it more carefully.

Design (PP: orthogonality): cut *detection* stays in longform.py ("what is
removable from the words"); cut *pacing* lives here ("which of those to keep,
where their edges land, how to label them"). The two compose; neither knows the
other's internals beyond the EditCut dataclass.
"""

from __future__ import annotations

import math
from dataclasses import dataclass
from typing import Any

from lumr_studio.engine.audio_boundaries import (
    SILENCE_SAFETY,
    Silence,
    _clamp_out_of_words,
    _inside_word,
    _word_spans,
    nearest_silence,
)
from lumr_studio.engine.longform import (
    EDIT_LEVELS,
    EditCut,
    _CORE_FILLERS,
    _merge_overlapping,
    detect_edit_cuts,
)

# The level/density knob. ``level`` is the longform aggression level (1..5);
# ``density`` scales how many of that level's candidates survive (0..1), so the
# editor can dial pace *within* a level without jumping to the next one.
#
# These two stay as the INTERNAL knobs (and the back-compat API) but are no longer
# what the editor surfaces. The redesign replaces them with two intuitive knobs —
# GAP-LENGTH and RHYTHM (see below) — that ``plan_microcuts`` prefers when given.
MIN_LEVEL = min(EDIT_LEVELS)
MAX_LEVEL = max(EDIT_LEVELS)
DEFAULT_LEVEL = 3
DEFAULT_DENSITY = 1.0

# ── GAP-LENGTH knob (replaces the abstract level) ─────────────────────────────
# "Cut pauses longer than X seconds." A CONTINUOUS minimum-pause threshold that
# directly sets which gaps are cuttable: a silence/pause shorter than this is
# kept. LOWER = more aggressive (cuts shorter pauses); HIGHER = gentler.
#
# Why a seconds value beats the 1-5 level: the old level mapped to discrete
# pause_thresholds (L2=1.0s, L3=0.5s — a 2x jump, the "cliff" Ashley hit at
# L2→L3). Gap-length is the SAME underlying quantity (the pause threshold) but
# continuous, so the editor slides smoothly from gentle to aggressive with no
# cliff. It feeds BOTH cut sources: the measured-silence floor (the bulk of cuts,
# ``silence_microcuts``) uses it verbatim as ``min_dur``, and the word-gap /
# filler / stutter detector picks the discrete level whose pause_threshold is
# nearest (``_level_for_gap_length``) so its richer filler logic still runs.
GAP_LENGTH_MIN = 0.15
GAP_LENGTH_MAX = 1.5
DEFAULT_GAP_LENGTH = 0.4

# ── RHYTHM knob (replaces the density fraction) ───────────────────────────────
# A 1-5 dial for rapid-succession density. Gap-length QUALIFIES which gaps are
# cuttable; RHYTHM then THINS the qualifying cuts by SPACING. ``S(r)`` is the
# minimum kept-content (seconds of surviving material) required between two
# consecutive APPLIED cuts:
#
#   r = 5 → S = 0.0   no constraint — every qualifying cut fires (back-to-back
#                     0.2s machine-gun cuts included).
#   r = 4 → S = 0.5   bars only the tightest rapid-fire clusters.
#   r = 3 → S = 1.2   the MIDDLE: visibly de-clusters 0.2s rapid-fire while the
#                     big pause cuts (spaced > 1.2s apart) all survive.
#   r = 2 → S = 2.0   spreads cuts further; keeps the impactful pauses only.
#   r = 1 → S = 3.0   gentlest rhythm — cuts must be ~3s of content apart.
#
# When two qualifying cuts are closer than ``S`` (measured as the KEPT gap
# between them — cut[i].start - cut[i-1].end), the LONGER-pause cut wins and the
# other is dropped (a greedy, longest-impact-first sweep — see ``_apply_rhythm``).
# Lower rhythm keeps the longer/more-impactful pauses and skips the closely-
# clustered short ones, exactly the "don't fire 0.2s cuts in a row" ask.
#
# The curve is tuned so the MIDDLE (r=3) is the meaningful de-cluster point:
# 1.2s of kept content is far wider than a 0.2s machine-gun gap (those collapse)
# yet narrower than the spacing between genuine sentence pauses (those survive).
RHYTHM_MIN = 1
RHYTHM_MAX = 5
DEFAULT_RHYTHM = 5
_RHYTHM_SPACING: dict[int, float] = {5: 0.0, 4: 0.5, 3: 1.2, 2: 2.0, 1: 3.0}


def _finite(value: Any, default: float) -> float:
    """``float(value)`` when it is finite, else ``default``.

    NaN / ±Infinity make every ``min``/``max`` clamp below return order-dependent
    garbage (NaN compares False against everything, so ``min(hi, nan)`` yields
    ``hi`` purely from argument order — a raw NaN rhythm silently snapped the micro
    layer to an extreme, and a non-finite nudge pushed an edge to NaN/±inf and
    emitted it as a cut boundary, which then serialized as invalid JSON). Coercing
    a non-finite knob to its neutral default HERE, before any clamp/arithmetic,
    makes the pacing math non-finite-safe BY CONSTRUCTION: the output can never be
    NaN and never branches on argument order. A finite value passes straight
    through, so integer/finite behaviour stays byte-identical.
    """
    try:
        v = float(value)
    except (TypeError, ValueError):
        return default
    return v if math.isfinite(v) else default


def _level_for_gap_length(gap_length: float) -> int:
    """The discrete aggression level whose ``pause_threshold`` is nearest ``gap_length``.

    Gap-length is continuous; ``detect_edit_cuts`` (the word-gap + filler +
    stutter detector) only speaks the 1-5 level vocabulary. So the silence FLOOR
    takes ``gap_length`` verbatim (continuous), and the word-gap path runs at the
    nearest level — close enough that its pauses align with the floor, while its
    filler/stutter richness (which the floor doesn't produce) still fires. Ties
    break toward the MORE aggressive level (smaller threshold) so a value exactly
    between two levels leans to cut, matching "lower gap_length = cut more".
    """
    g = max(GAP_LENGTH_MIN, min(GAP_LENGTH_MAX, float(gap_length)))
    # nearest by |pause_threshold - g|; tie → smaller threshold (more aggressive)
    return min(
        EDIT_LEVELS,
        key=lambda lv: (abs(EDIT_LEVELS[lv].pause_threshold - g),
                        EDIT_LEVELS[lv].pause_threshold),
    )


def _spacing_for_rhythm(rhythm: float) -> float:
    """Minimum kept-content spacing ``S(r)`` between consecutive applied cuts.

    The RHYTHM → spacing curve (see ``_RHYTHM_SPACING``), now CONTINUOUS: the
    slider hands a float, so a fractional rhythm interpolates piecewise-LINEARLY
    between the integer anchors (e.g. r = 3.5 lands strictly between the r=3 and
    r=4 spacings). ``r = 5`` → 0 (no thinning); lower ``r`` → wider required
    spacing, so rapid-fire clusters thin out while the impactful pauses survive.

    Integer rhythms return their EXACT anchor value (the ``frac == 0`` snap, no
    float drift), so an old integer save paces identically. Out-of-range clamps
    to ``[RHYTHM_MIN, RHYTHM_MAX]``.
    """
    # Sanitize FIRST: a non-finite rhythm (NaN/±inf) becomes the neutral default
    # DEFAULT_RHYTHM, so the clamp below can't return order-dependent garbage on a
    # NaN (where every comparison is False). A finite rhythm is unchanged.
    r = max(float(RHYTHM_MIN), min(float(RHYTHM_MAX), _finite(rhythm, DEFAULT_RHYTHM)))
    lo = int(r)  # floor (r >= 1, so truncation IS the floor); the lower anchor
    frac = r - lo
    if frac == 0.0:  # integer rhythm — pin the anchor exactly, no interpolation
        return _RHYTHM_SPACING[lo]
    # piecewise-linear blend toward the next (lo + 1) anchor
    return _RHYTHM_SPACING[lo] + (_RHYTHM_SPACING[lo + 1] - _RHYTHM_SPACING[lo]) * frac


# Migration: an OLD saved edit (or an older client) carries ``level``/``density``
# instead of ``gap_length``/``rhythm``. These map the legacy knobs onto the new
# ones so an existing save still loads at a sensible pace.
#   level → gap_length : the level's OLD silence floor
#                        (``_silence_threshold_for_level``), clamped to the
#                        gap-length range. gap_length sets the silence floor —
#                        the bulk of the cuts — verbatim, so migrating from that
#                        floor (NOT the larger word-gap ``pause_threshold``)
#                        reproduces the level's original cut count. So L3 → 0.30s,
#                        L4 → 0.21s, L1 → 1.2s, L5 → 0.09s clamped to 0.15s.
#   density → rhythm   : density is "keep this fraction"; rhythm is "space cuts
#                        out". 1.0 (keep all) → 5 (no spacing); lower density →
#                        lower rhythm (more thinning). A linear bucket across the
#                        five rhythm steps.


def gap_length_for_level(level: int) -> float:
    """Migrate a legacy ``level`` (1..5) to a ``gap_length`` in seconds.

    Returns the level's OLD measured-silence floor (``_silence_threshold_for_level``),
    clamped into the gap-length range. gap_length feeds the silence floor verbatim,
    and that floor produces the bulk of the cuts — so migrating from the silence
    floor (NOT the word-gap ``pause_threshold``, which is a different, larger value)
    is what reproduces the level's original cut count. Using ``pause_threshold`` here
    raised the floor and silently gentled every migrated save (default L3 went
    30 → 17 cuts).
    """
    lv = max(MIN_LEVEL, min(MAX_LEVEL, int(level)))
    return max(GAP_LENGTH_MIN, min(GAP_LENGTH_MAX, _silence_threshold_for_level(lv)))


def rhythm_for_density(density: float) -> int:
    """Migrate a legacy ``density`` (0..1) to a ``rhythm`` (1..5).

    Density was a keep-fraction (1.0 = keep all); rhythm is a spacing dial
    (5 = no spacing). They share a direction — more density ≈ more cuts ≈ higher
    rhythm — so this buckets the 0..1 fraction linearly onto 1..5: 1.0 → 5,
    ~0.8 → 4, ... 0.0 → 1. Not an exact inverse (density thinned by count,
    rhythm thins by spacing), but a sensible, monotonic restore of intent.
    """
    d = max(0.0, min(1.0, float(density)))
    return max(RHYTHM_MIN, min(RHYTHM_MAX, 1 + round(d * (RHYTHM_MAX - RHYTHM_MIN))))

# How far a micro-cut edge will reach to find a measured silence to land on.
# Pairs with audio_boundaries.snap_cuts_to_silence's default window.
SILENCE_SNAP_WINDOW = 0.20
# Cushion left on the kept side so an edge never sits exactly on a voicing
# onset/offset (matches snap_cuts_to_silence's safety_margin). Single source of
# truth lives in audio_boundaries and is IMPORTED above; this module re-exports
# it (the import binds the name here) so callers that read
# ``microcut_pacing.SILENCE_SAFETY`` keep working. DRY: one value, two names.

# ── Silence -> cut conversion (FIX 1) ─────────────────────────────────────────
# Emit a micro-cut from a MEASURED silence (audio_boundaries grid), not only
# from inter-word timestamp gaps. The word-gap detector is blind to dead-air
# wherever adjacent words are butt-joined (zero reported gap) even though the
# AUDIO is silent there -- 84% of episode #4's word pairs. This threshold is the
# minimum measured-silence length that becomes a cut.
#
# Tuned EMPIRICALLY against Ashley's #4 cut-review inbox (the spots she added by
# hand where a silence was measured but no micro-cut was emitted):
#   threshold  new count  found-not-cut adds covered (of 27)
#     0.50          ~201          22
#     0.40          ~249          24
#     0.35          ~276          24
#     0.30          ~298          26   <- chosen
#     0.28          ~306          27
# 0.30s covers 26/27 of the dead-air spots she added while holding the cut count
# near 20% of the raw 0.05s grid (1495 silences) -- nowhere near "cut every gap".
# The lone miss is a pair of ~0.29s sub-silences; dropping to 0.28 catches it for
# ~8 more cuts. It sits below level 3's 0.5s word-gap pause_threshold because her
# corrections prove she cuts tighter dead-air than that, yet well above the 0.05s
# grid floor (breath/plosive territory).
#
# This is the DEFAULT-level anchor: ``_silence_threshold_for_level`` scales it by
# the level's pause_threshold (Very Subtle ~1.2s ... Cut for Time ~0.1s), so the
# silence floor responds to the aggression knob instead of swamping levels 1-3.
MIN_SILENCE_CUT = 0.30

# How far the START edge reaches forward to land on the post-word measured
# silence (FIX 2). Wider than SILENCE_SNAP_WINDOW because a real breath/beat can
# sit 0.3-0.5s past the forced-aligned word end; the old 0.20s window left cut
# starts ~0.5s too early, eating the word's tail (Ashley's trims pushed the
# start +0.49s median). The end edge keeps the tighter SILENCE_SNAP_WINDOW.
START_SNAP_WINDOW = 0.60

# ── Scrap consolidation (merge over-chopped micro-cuts) ───────────────────────
# When rapid micro-cuts leave tiny KEPT scraps between them, the result is
# machine-gun chopping that shreds a span into meaningless bits — Ashley's batch-2
# complaint: one span fired 5 micro-cuts in 3.6s over a string of "ah ah ah ah ah"
# fillers, leaving four ~0.2–0.4s "ah" scraps she had to clean up by hand. The
# consolidation post-pass merges two cuts (and the scrap between them) into one
# continuous cut when the scrap is shorter than this threshold AND holds no
# CONTENT span — a non-lexical hesitation ("ah"/"um") is not content, so a
# filler-only scrap is "near-empty" and gets swallowed; a scrap with any real
# word (or a vocalization) is protected, so a merge NEVER crosses real speech.
#
# Tuned against episode #4's planned cuts (the exact 296 Ashley reviewed). The
# filler-only scraps inside the over-chopped "ah ah ah ah ah" cluster run up to
# 0.389s; the next filler-only scrap above the cluster sits at 0.409s, so 0.40 is
# the natural valley and the MINIMUM threshold that collapses that 5-cut/3.6s
# cluster down to its floor (consolidation-only on the live 296 cuts):
#   threshold  cluster cuts  total cuts (of 296)
#     0.30          4            291
#     0.38          3            290
#     0.40          2            289   <- chosen (cluster reaches its floor here)
#     0.45          2            288
# The cluster floor is 2, not 1: a protected [vocalization] event sits in one of
# the inner scraps, and a merge must never swallow a vocalization (the S3
# invariant) — so that one split survives by design. Only 7 of 296 cuts merge at
# 0.40, every one a filler/silence-only scrap.
#
# The CONTENT guard — not the threshold — is the real safety: real-word scraps
# run as short as 0.226s (below 0.40) yet are never merged, because a content
# word protects them. Raising the threshold only swallows more empty scrap; it
# can never merge across speech. Detecting "wordy rambling" (real words that
# together say nothing) and true rhythm/intentional-pause judgment are
# deliberately OUT of scope here — reserved for a later LLM editing brain.
SCRAP_MERGE_MAX = 0.40


# ── Reason strings the inspector renders ──────────────────────────────────────


def clarify_reason(cut: EditCut) -> str:
    """A clean, human ``reason`` for the micro-cut inspector row.

    ``detect_edit_cuts`` already labels each cut, but merged cuts carry stacked
    labels ("pause: 1.1s; filler: um") and the verbs differ ("repeat:" vs the
    word "stutter" Ashley uses). This normalizes to the inspector's vocabulary:

      * a pure pause      -> ``"pause: 2.3s"``
      * a pure filler     -> ``"filler: um"``
      * a stutter/repeat  -> ``"stutter: the the"``
      * a merged span     -> the dominant kind + a "+N more" tail, e.g.
                             ``"pause: 1.1s (+1 more)"``

    The classification is *pause-vs-filler-vs-stutter*, cleaner than the raw
    string so the inspector can colour/group rows. Pure presentation -- it never
    changes the cut's timing.
    """
    parts = [p.strip() for p in cut.reason.split(";") if p.strip()]
    if not parts:
        return f"pause: {cut.duration:.1f}s"

    head = parts[0]
    kind, _, detail = head.partition(":")
    kind = kind.strip().lower()
    detail = detail.strip()

    if kind == "repeat":
        # "repeat: the" -> "stutter: the the" (the stammered pair, as heard).
        label = f"stutter: {detail} {detail}" if detail else "stutter"
    elif kind == "filler":
        label = f"filler: {detail}" if detail else "filler"
    elif kind == "pause":
        # Prefer the measured duration; the raw "2.3s" can drift after merges.
        label = f"pause: {cut.duration:.1f}s"
    else:
        label = head

    extra = len(parts) - 1
    if extra > 0:
        label = f"{label} (+{extra} more)"
    return label


def classify(cut: EditCut) -> str:
    """The micro-cut's dominant kind: ``"pause"`` | ``"filler"`` | ``"stutter"``.

    Reads the leading label of the (possibly merged) reason. Used for grouping,
    density weighting, and tests.
    """
    head = cut.reason.split(";")[0]
    kind = head.split(":")[0].strip().lower()
    if kind == "repeat":
        return "stutter"
    if kind in {"pause", "filler"}:
        return kind
    return "pause"


# ── Kept-material intersection (StoryMap beats) ───────────────────────────────


def kept_ranges_from_beats(
    story_map: dict[str, Any] | None,
    duration: float | None = None,
) -> list[tuple[float, float]]:
    """The time ranges the editor KEEPS, from the StoryMap's non-cut beats.

    A beat is kept unless its ``intent == "cut"`` (the 00-CONTRACT keep rule).
    Adjacent kept beats are merged so a micro-cut spanning a beat seam isn't
    split needlessly.

    Returns ``[(start, end), ...]`` sorted, non-overlapping. With no StoryMap we
    return a single all-content range (``[(0, duration)]`` if ``duration`` is
    known, else an empty list meaning "no constraint" -- callers treat empty as
    unconstrained).
    """
    beats = (story_map or {}).get("beats") if story_map else None
    if not beats:
        if duration is not None and duration > 0:
            return [(0.0, float(duration))]
        return []

    kept = [
        (float(b["start"]), float(b["end"]))
        for b in beats
        if b.get("intent") != "cut"
    ]
    kept.sort(key=lambda r: r[0])

    merged: list[tuple[float, float]] = []
    for s, e in kept:
        if merged and s <= merged[-1][1] + 1e-6:
            merged[-1] = (merged[-1][0], max(merged[-1][1], e))
        else:
            merged.append((s, e))
    return merged


def _clip_to_kept(
    cut: EditCut, kept: list[tuple[float, float]]
) -> EditCut | None:
    """Trim a micro-cut to the kept range it sits in; drop it if it sits in none.

    A micro-cut that straddles a kept/cut seam is trimmed to the kept side so we
    never micro-cut material the model already removed (that span is gone
    anyway, and a cut hanging off the edge of a kept range produces a bad seam).
    Empty ``kept`` means "no constraint" -- the cut passes through unchanged.
    """
    if not kept:
        return cut
    for ks, ke in kept:
        if cut.start < ke and cut.end > ks:  # overlaps this kept range
            ns = max(cut.start, ks)
            ne = min(cut.end, ke)
            if ne - ns <= 0:
                return None
            if ns == cut.start and ne == cut.end:
                return cut
            return EditCut(start=ns, end=ne, reason=cut.reason)
    return None


# ── Land edges on measured silence (S0) ───────────────────────────────────────


def _content_spans(words: list[dict]) -> list[tuple[float, float]]:
    """Spans the consolidation merge must NOT swallow: content words + events.

    A kept scrap between two micro-cuts is "near-empty" (mergeable) only if no
    such span lands in it. CONTENT = every spoken token EXCEPT the non-lexical
    hesitation sounds (``_CORE_FILLERS``: um/uh/er/ah/...). A scrap holding only
    an "ah" is near-empty — that is the "ah ah ah ah ah" over-chop consolidation
    collapses — but a scrap with any real word ("and"/"like" included, since they
    can be load-bearing) is protected. Vocalization events (laughter/gasps) count
    as content too, so a merge never swallows one (the S3 vocalization invariant).
    """
    out: list[tuple[float, float]] = []
    for w in words:
        if "start" not in w or "end" not in w:
            continue
        if w.get("type") == "event":
            out.append((float(w["start"]), float(w["end"])))
            continue
        token = str(w.get("word", "")).strip().lower().strip(".,!?;:\"'")
        if not token or token in _CORE_FILLERS:
            continue
        out.append((float(w["start"]), float(w["end"])))
    out.sort()
    return out


def _overlaps_kept(s: float, e: float, kept: list[tuple[float, float]]) -> bool:
    """True if ``[s, e)`` overlaps any kept range (empty kept = unconstrained)."""
    if not kept:
        return True
    return any(s < ke and e > ks for ks, ke in kept)


def _next_silence_onset(
    t: float, silences: list[Silence], window: float, min_dur: float
) -> float | None:
    """Onset of the next substantial measured silence at/after ``t``.

    The dead-air a cut is really removing starts here; used by the FIX 2 start
    snap to push a cut start forward off the word tail and onto the silence.
    Only silences at least ``min_dur`` long count (a 50ms tail-silence isn't the
    pause), and only those whose onset is within ``window`` ahead of ``t``.
    """
    best: float | None = None
    for sil in silences:
        if sil.duration < min_dur:
            continue
        if t <= sil.start <= t + window:
            if best is None or sil.start < best:
                best = sil.start
    return best


# ── Silence-grid candidates (FIX 1) ───────────────────────────────────────────


def silence_microcuts(
    silences: list[Silence],
    kept: list[tuple[float, float]],
    word_spans: list[tuple[float, float]],
    *,
    min_dur: float = MIN_SILENCE_CUT,
    safety: float = SILENCE_SAFETY,
) -> list[EditCut]:
    """Micro-cuts straight off the MEASURED silence grid (audio_boundaries).

    The companion to ``detect_edit_cuts``' word-gap pauses: that one only sees
    dead-air where the word timestamps report a gap, so it misses silence inside
    butt-joined word pairs (84% of #4). This reads the audio's own silences
    instead -- every measured silence at least ``min_dur`` long, inside kept
    material, becomes a removable span.

    Word-safety is enforced structurally: edges are pulled ``safety`` inward and
    then clamped out of any word they still land in (forced-alignment wobble can
    poke a word edge a few ms into a measured silence). A span that collapses or
    can't be made word-safe is dropped. These cuts are level-independent -- they
    come from the audio, not the aggression knob -- so they're a constant floor
    that ``plan_microcuts`` unions with the word-gap/filler/stutter candidates.
    """
    cuts: list[EditCut] = []
    for sil in silences:
        if sil.duration < min_dur:
            continue
        safe = _clamp_out_of_words(sil.start + safety, sil.end - safety, word_spans, safety)
        if safe is None:
            continue
        s, e = safe
        if not _overlaps_kept(s, e, kept):
            continue
        cuts.append(EditCut(start=s, end=e, reason=f"pause: {sil.duration:.1f}s"))
    return cuts


def _silence_threshold_for_level(level: int) -> float:
    """The measured-silence -> cut threshold for an aggression ``level``.

    Anchored at ``MIN_SILENCE_CUT`` for the default level and scaled by the
    level's word-gap ``pause_threshold``, so the silence floor tracks the SAME
    aggression knob as the word gaps (one concept, not two): "Very Subtle" cuts
    only long dead-air (~1.2s), "Cut for Time" cuts down to ~0.1s. A flat,
    level-independent floor would otherwise swamp levels 1-3 into near-identical
    edits and break the "raising the level removes more" invariant.
    """
    base = EDIT_LEVELS[DEFAULT_LEVEL].pause_threshold
    return MIN_SILENCE_CUT * EDIT_LEVELS[level].pause_threshold / base


def snap_microcut_to_silence(
    cut: EditCut,
    silences: list[Silence],
    word_spans: list[tuple[float, float]],
    window: float = SILENCE_SNAP_WINDOW,
    safety: float = SILENCE_SAFETY,
    start_window: float | None = None,
) -> EditCut | None:
    """Move a micro-cut's edges onto the nearest S0 measured silence.

    Mirrors ``audio_boundaries.snap_cuts_to_silence`` but on a single EditCut and
    with a clip-protection guarantee: an edge only moves if the move keeps it out
    of a spoken word. If snapping would land an edge *inside* a word, that edge
    stays where detect_edit_cuts put it (which is already a word boundary). Either
    way the returned cut never has an edge strictly inside a word.

    FIX 2 (start margin): the START edge is forward-aware. When the start
    already sits inside a measured silence, it lands on that silence's onset (the
    established S0 snap). When it sits in the preceding word's TAIL/breath (no
    enclosing silence), it reaches FORWARD up to ``start_window`` to the next
    dead-air onset, so the tail is kept instead of eaten -- the start runs ~0.5s
    early otherwise (Ashley's trims pushed it +0.49s median). Forward-only: a
    start is never pushed earlier into the tail. ``start_window`` never reaches
    less far than ``window``.

    Returns the snapped cut, or ``None`` if it collapsed to zero width.
    """
    sw = START_SNAP_WINDOW if start_window is None else start_window
    sw = max(sw, window)
    s, e = cut.start, cut.end

    sil_e = nearest_silence(e, silences, window)
    if sil_e is not None:
        cand = sil_e.end - safety
        if cand > s and not _inside_word(cand, word_spans):
            e = cand

    sil_s = nearest_silence(s, silences, window)
    if sil_s is not None and sil_s.contains(s):
        # Already in measured silence: land on its onset (audio is quiet there).
        cand = sil_s.start + safety
        if cand < e and not _inside_word(cand, word_spans):
            s = cand
    else:
        # In the word tail: push forward onto the real dead-air onset, keeping
        # the tail. Never earlier than the current start.
        onset = _next_silence_onset(s, silences, sw, MIN_SILENCE_CUT)
        if onset is not None:
            cand = onset + safety
            if s < cand < e and not _inside_word(cand, word_spans):
                s = cand

    if e - s <= 0:
        return None
    return EditCut(start=s, end=e, reason=cut.reason)


# ── Density knob ──────────────────────────────────────────────────────────────


def _apply_density(
    cuts: list[EditCut], density: float
) -> list[EditCut]:
    """Keep a ``density`` fraction of candidate cuts, smallest-impact first.

    ``density == 1.0`` keeps all (the level's full aggression). Lower values drop
    the shortest cuts first -- they remove the least content, so trimming them
    loosens pace with the smallest visible change. ``density <= 0`` keeps none.
    This lets the editor dial pace *within* a level instead of only between
    levels (5 coarse steps -> a continuous knob).
    """
    if density >= 1.0 or not cuts:
        return cuts
    if density <= 0.0:
        return []
    keep_n = max(1, round(len(cuts) * density))
    if keep_n >= len(cuts):
        return cuts
    # Rank by duration descending; keep the top-N highest-impact cuts.
    ranked = sorted(cuts, key=lambda c: c.duration, reverse=True)[:keep_n]
    ranked.sort(key=lambda c: c.start)
    return ranked


# ── Rhythm knob (spacing thinner) ─────────────────────────────────────────────


def _apply_rhythm(cuts: list[EditCut], spacing: float) -> list[EditCut]:
    """Thin qualifying cuts so consecutive applied cuts are ``spacing`` apart.

    The RHYTHM pass (see ``_RHYTHM_SPACING`` / ``_spacing_for_rhythm``). Gap-length
    already QUALIFIED these cuts (each is a long-enough pause); rhythm now enforces
    a minimum KEPT-content gap between the ones we actually apply, so the editor
    won't fire 0.2s cuts back-to-back at lower rhythm.

    ``spacing <= 0`` (rhythm 5) keeps everything. Otherwise a greedy, longest-
    pause-first sweep: walk cuts by DURATION descending (the most impactful pause
    wins ties for the same neighbourhood) and accept one only when the KEPT gap to
    every already-accepted cut is at least ``spacing``. The kept gap between two
    cuts is ``later.start - earlier.end`` — the surviving content between them —
    so two rapid 0.2s cuts 0.15s apart collapse to the longer one, while two big
    pauses several seconds apart both survive. Output is re-sorted by start.

    Word-safety is untouched: this only ever DROPS whole cuts (never edits an
    edge), so every surviving cut keeps the word-safe edges plan_microcuts gave it.
    """
    if spacing <= 0 or len(cuts) < 2:
        return cuts
    # Most impactful first; on equal duration, earlier start wins for stability.
    order = sorted(cuts, key=lambda c: (-c.duration, c.start))
    accepted: list[EditCut] = []
    for cut in order:
        ok = True
        for a in accepted:
            # kept content between the two cuts (whichever is earlier)
            gap = cut.start - a.end if cut.start >= a.end else a.start - cut.end
            if gap < spacing:
                ok = False
                break
        if ok:
            accepted.append(cut)
    accepted.sort(key=lambda c: c.start)
    return accepted


# ── Scrap consolidation ───────────────────────────────────────────────────────


def _consolidate_microcuts(
    cuts: list[EditCut],
    content_spans: list[tuple[float, float]],
    max_scrap: float = SCRAP_MERGE_MAX,
) -> list[EditCut]:
    """Merge rapid micro-cuts split by tiny near-empty scraps into clean cuts.

    Post-pass over the planned (sorted, non-overlapping) micro-cuts. Two adjacent
    cuts collapse into one — swallowing the KEPT scrap between them — when that
    scrap is shorter than ``max_scrap`` AND holds no content span (a real word or
    a vocalization; see ``_content_spans``). Applied TRANSITIVELY: a run of N
    rapid cuts over filler/silence-only scraps becomes a single continuous cut, so
    an over-chopped span ("ah ah ah ah ah") goes as ONE cut instead of little
    bits.

    Word-safe by construction. The merged cut's edges are the OUTER cuts' edges,
    which were already word-safe; the scrap in the middle is swallowed only when
    it carries no content span — so a merge never lands an edge inside a word and
    never deletes a real word. Cuts with any content word between them are left
    untouched: distinguishing a meaningful pause there from rambling is rhythm
    judgment, deliberately out of scope (the LLM editing brain's job).
    """
    if len(cuts) < 2:
        return cuts

    def scrap_clear(s: float, e: float) -> bool:
        """True if the open scrap ``(s, e)`` holds no content span (mergeable)."""
        for ws, we in content_spans:
            if we > s and ws < e:  # any overlap with the scrap interior
                return False
            if ws >= e:  # spans sorted; nothing later can overlap
                break
        return True

    merged: list[EditCut] = [cuts[0]]
    for cut in cuts[1:]:
        prev = merged[-1]
        scrap = cut.start - prev.end
        if scrap < max_scrap and scrap_clear(prev.end, cut.start):
            merged[-1] = EditCut(
                start=prev.start,
                end=max(prev.end, cut.end),
                reason=f"{prev.reason}; {cut.reason}",
            )
        else:
            merged.append(cut)
    return merged


# ── The pacing producer ───────────────────────────────────────────────────────


def plan_microcuts(
    words: list[dict],
    *,
    level: int = DEFAULT_LEVEL,
    density: float = DEFAULT_DENSITY,
    gap_length: float | None = None,
    rhythm: float | None = None,
    story_map: dict[str, Any] | None = None,
    silences: list[Silence] | None = None,
    duration: float | None = None,
) -> list[dict[str, Any]]:
    """Produce paced micro-cuts in the ``/api/microcuts`` shape ``[{start,end,reason}]``.

    The S3 pipeline, in order:

      1. ``detect_edit_cuts(words, level)`` -- the longform candidates at this
         aggression (pauses + fillers + stutters), with vocalizations already
         protected.
      1b. ``silence_microcuts(silences, ...)`` (FIX 1) -- candidates straight off
         the MEASURED silence grid, catching dead-air the word gaps miss because
         the words are butt-joined. Only when ``silences`` is supplied.
      2. intersect with the StoryMap's KEPT beats -- micro-cuts only inside kept
         material (the within-beat jump-cuts; cut-intent beats are removed whole
         elsewhere).
      3. land edges on S0 measured silences -- so no edge clips a word, and the
         START edge reaches the post-word silence (FIX 2) instead of eating the
         word tail.
      3b. union overlapping candidates so the silence-grid and word-gap cuts
         dedupe into single spans.
      4. apply the RHYTHM knob -- thin the qualifying cuts by spacing (drop the
         closely-clustered short cuts, keep the impactful pauses); the legacy
         DENSITY knob (keep-a-fraction) runs instead when ``rhythm`` is None.
      5. clean ``reason`` strings for the inspector.

    The aggression knobs are the redesigned GAP-LENGTH + RHYTHM pair; the legacy
    ``level``/``density`` remain accepted for back-compat (old saves, older
    callers) but ``gap_length``/``rhythm`` win whenever they are supplied.

    Args:
        words: Hammy word list (ideally S0 forced-aligned). Event tokens carry
            the vocalization protection.
        level: legacy longform aggression 1..5. Higher -> more, shorter cuts.
            Used only when ``gap_length`` is None.
        density: legacy 0..1 fraction of the level's cuts to keep (1.0 = all).
            Used only when ``rhythm`` is None.
        gap_length: PREFERRED — the minimum pause/silence in seconds that becomes
            cuttable (``GAP_LENGTH_MIN``..``GAP_LENGTH_MAX``). Sets the silence
            floor verbatim and selects the nearest word-gap level. Lower = cut
            shorter pauses (more aggressive). When given it OVERRIDES ``level``.
        rhythm: PREFERRED — 1..5 rapid-succession dial (fractional ok; the curve
            interpolates). 5 = apply every qualifying cut; lower spaces applied
            cuts out (``_RHYTHM_SPACING``), dropping the closely-clustered short
            cuts and keeping the impactful pauses. When given it OVERRIDES
            ``density``.
        story_map: S4 StoryMap; its non-cut beats define kept material. None ->
            unconstrained (whole timeline kept).
        silences: S0 measured silences. Drive two things: (1) extra cut
            candidates from the silence grid (FIX 1), and (2) edge-snapping. None
            -> neither (cuts come only from word gaps, edges on word boundaries).
        duration: total source length, only used to bound the kept range when
            there's no StoryMap.

    Returns:
        ``[{start, end, reason}, ...]`` sorted by start, the locked contract
        shape. Every edge is a word boundary or a measured-silence edge; none
        clips a word; none falls inside a cut-intent beat.
    """
    # Resolve the aggression knobs. GAP-LENGTH / RHYTHM are the redesigned
    # controls and WIN when supplied; otherwise fall back to legacy level/density.
    #   gap_length → the silence floor verbatim + the nearest word-gap level
    #   rhythm     → a kept-content spacing the thinner enforces
    if gap_length is not None:
        # Sanitize before clamping: a non-finite gap_length → the neutral default,
        # so the clamp can't snap to an extreme on a NaN/inf (see ``_finite``).
        gap_length = max(GAP_LENGTH_MIN, min(GAP_LENGTH_MAX, _finite(gap_length, DEFAULT_GAP_LENGTH)))
        level = _level_for_gap_length(gap_length)
        silence_threshold = gap_length
    else:
        level = max(MIN_LEVEL, min(MAX_LEVEL, int(level)))
        # legacy: the silence floor scales with the chosen level
        silence_threshold = _silence_threshold_for_level(level)

    candidates = detect_edit_cuts(words, level)

    kept = kept_ranges_from_beats(story_map, duration)
    spans = _word_spans(words)
    sils = silences or []

    # FIX 1: add measured-silence candidates -- the dead-air the word-gap
    # detector is blind to. The threshold is GAP-LENGTH verbatim (the redesigned
    # knob's whole point: a continuous seconds value drives the cut floor with no
    # L2->L3 cliff); on the legacy path it scales with the level instead.
    if sils:
        candidates = candidates + silence_microcuts(
            sils, kept, spans, min_dur=silence_threshold
        )

    paced: list[EditCut] = []
    for cut in candidates:
        clipped = _clip_to_kept(cut, kept)
        if clipped is None:
            continue
        if sils:
            snapped = snap_microcut_to_silence(clipped, sils, spans)
            if snapped is None:
                continue
            # Re-clip in case a silence edge reached past the kept range.
            snapped = _clip_to_kept(snapped, kept)
            if snapped is None:
                continue
            clipped = snapped
        # Final word-safety backstop: a filler/word cut can carry an edge that
        # sits inside a *different*, overlapping forced-aligned word (alignment
        # artifact). Drop/trim such edges so the invariant holds unconditionally.
        safe = _clamp_out_of_words(clipped.start, clipped.end, spans, SILENCE_SAFETY)
        if safe is None:
            continue
        if (safe[0], safe[1]) != (clipped.start, clipped.end):
            clipped = EditCut(start=safe[0], end=safe[1], reason=clipped.reason)
        paced.append(clipped)

    # FIX 1: union overlapping candidates so a measured silence and the word-gap
    # pause beside it collapse into one cut (dedupe), rather than double-counting.
    paced.sort(key=lambda c: c.start)
    paced = _merge_overlapping(paced)

    # Consolidation: collapse rapid micro-cuts separated by a tiny near-empty
    # scrap (no content word/vocalization) into one clean cut, so an over-chopped
    # span isn't left as little bits. Word-safe — a scrap with any real word is
    # protected. Runs before density so the knob thins the consolidated set.
    paced = _consolidate_microcuts(paced, _content_spans(words))

    # Thin the qualifying cuts. RHYTHM (spacing) wins when supplied — it spaces
    # applied cuts out so rapid-fire 0.2s clusters drop while big pauses survive;
    # otherwise the legacy DENSITY (keep-fraction) thinner runs. Both only DROP
    # whole cuts, so word-safe edges are untouched.
    if rhythm is not None:
        paced = _apply_rhythm(paced, _spacing_for_rhythm(rhythm))
    else:
        # Sanitize density too: a non-finite legacy density would make
        # _apply_density's round() raise; coerce to the neutral default (keep-all).
        paced = _apply_density(paced, _finite(density, DEFAULT_DENSITY))
    paced.sort(key=lambda c: c.start)

    return [
        {"start": c.start, "end": c.end, "reason": clarify_reason(c)}
        for c in paced
    ]


# ── GLOBAL cut-transition nudge ───────────────────────────────────────────────
# Two millisecond knobs that uniformly shift every ALGORITHM cut edge AFTER the
# pacing layer (plan_microcuts → refine_onsets) has placed and word-safed it. The
# ONE shared transform both the serve path (editor_server.microcuts_payload) and
# the export path call, so what the editor previews is byte-identical to what the
# render emits (preview == export by construction).
#
# SIGN (documented, load-bearing — the editor's edge labels depend on it):
#   leadInMs  shifts each cut's TRAILING edge (``end``, the resume point). A
#             POSITIVE value pulls the resume EARLIER, leaving MORE AIR before the
#             next word (a softer, less abrupt resume):  end'  = end  - leadInMs/1000
#   tailOutMs shifts each cut's LEADING edge (``start``, the outgoing point). A
#             POSITIVE value pushes the cut start LATER, KEEPING MORE TAIL after
#             the previous word:                         start' = start + tailOutMs/1000
#
# Every shifted edge is RE-CLAMPED through ``_clamp_out_of_words`` (the shared
# word-clip backstop), so a nudge can never land an edge strictly inside a kept
# word — a clipping nudge is bounded to the word boundary. A nudge that would
# collapse a cut entirely leaves that cut at its original (already word-safe)
# edges rather than dropping it; the rule is deterministic, so both paths agree.
def apply_transition_nudge(
    cuts: list[dict[str, Any]],
    lead_in_ms: float = 0.0,
    tail_out_ms: float = 0.0,
    words: list[dict] | None = None,
) -> list[dict[str, Any]]:
    """Uniformly shift each cut's edges by the lead-in / tail-out nudge, word-safe.

    Pure: returns a NEW list and never mutates the input cuts. With BOTH knobs 0
    it is the IDENTITY — the same list object is returned untouched — so the
    default pace is byte-for-byte the pre-nudge behaviour. See the module note
    above for the sign of each knob.

    Args:
        cuts: ``[{start, end, reason}, ...]`` (the ``/api/microcuts`` shape); any
            extra keys are preserved.
        lead_in_ms: POSITIVE leaves more air before the next word (trailing edge
            earlier). Milliseconds.
        tail_out_ms: POSITIVE keeps more tail after the previous word (leading
            edge later). Milliseconds.
        words: word list used to re-clamp every shifted edge out of kept words.
            Empty/None → only the collapse guard applies (no word grid to honour).

    Returns:
        A new ``[{start, end, ...}]`` list, every edge still word-safe.
    """
    # Sanitize FIRST: a non-finite lead/tail (NaN/±inf) would otherwise shift an
    # edge to NaN/±inf and emit it as a cut boundary (a NaN survives the word-clamp
    # and serializes as invalid JSON). Coerce to 0 — the no-nudge identity — so this
    # transform is non-finite-safe by construction (see ``_finite``).
    lead = _finite(lead_in_ms, 0.0)
    tail = _finite(tail_out_ms, 0.0)
    if lead == 0.0 and tail == 0.0:
        return cuts  # identity — no nudge, nothing to shift or re-clamp
    spans = _word_spans(words or [])
    lead_s = lead / 1000.0
    tail_s = tail / 1000.0
    out: list[dict[str, Any]] = []
    for c in cuts:
        # +tail pushes the leading edge later (more tail kept); +lead pulls the
        # trailing edge earlier (more air before the next word).
        s = float(c["start"]) + tail_s
        e = float(c["end"]) - lead_s
        nc = dict(c)
        safe = _clamp_out_of_words(s, e, spans, SILENCE_SAFETY)
        if safe is not None:
            nc["start"], nc["end"] = safe[0], safe[1]
        # safe is None → the nudge collapsed the cut or no clean edge exists; keep
        # the cut's ORIGINAL (already word-safe) edges rather than drop it.
        out.append(nc)
    return out
