# GENERATED by studio/tools/sync-engine.sh from clipforge/clipforge/render.py.
# Do not edit it: change the source and run the script. `sync-engine.sh --check` fails on drift.
"""
Final video export (the in-editor render).

The editor scrubs on a small PROXY (e.g. 640x360) so playback is instant, but a
real EXPORT must come from the full-resolution original. This module turns the
user's saved edit — expressed as REMOVED time-spans — into a finished mp4 by
keeping the complement of those spans, frame-accurately, from the highest-res
source available.

Pipeline (mirrors the proven /tmp/render_export.py spike, productionized):

    removed ranges                       (server: removed_ranges(edit, …))
      → word-clamp each span             (never clip a spoken word)
      → KEPT segments = complement over [0, duration]
      → ffmpeg filter_complex: trim/atrim each kept seg + setpts/asetpts
        + concat=n=K:v=1:a=1
      → libx264 High / yuv420p / crf 18–20, aac 192k, +faststart

Everything except the ffmpeg shell-out is pure and unit-tested; the encode is
driven through ``run_render`` which a test patches at the subprocess boundary.

Two source-resolution wrinkles this module owns:

  * proxy → full-res: the editor's ``video_path`` may be a downscaled proxy. We
    resolve the real source via (1) an explicit ``<video>.source`` sidecar, (2)
    the words-sidecar symlink (a ``*-proxy.words.json`` symlink points at the
    full-res transcript next to the original), (3) the ``*-proxy`` → original
    naming convention, then keep whichever candidate actually has more pixels.
  * resolution policy: export AT the source resolution, never upscale; only
    downscale when the source exceeds ~2160p (no pointless 4K from a 1080p
    master).
"""

from __future__ import annotations

import logging
import subprocess
import threading
from dataclasses import dataclass, field
from pathlib import Path

from lumr_studio.engine.audio_boundaries import (
    Silence,
    _containing_word,
    _inside_word,
    _word_spans,
    edge_lands_in_silence,
    refine_onsets,
)

logger = logging.getLogger(__name__)

# Merge/zero-length epsilon. Matches editor_server._MERGE_EPS so the kept-segment
# math agrees with the removed-range math the rest of the app uses.
_EPS = 0.001

# Video containers we'll consider when mapping a proxy stem back to its original.
_VIDEO_SUFFIXES = (".mp4", ".MP4", ".mov", ".MOV", ".m4v", ".mkv", ".webm")

# Resolution policy. Export at the source height, capped here. 1440p (2560x1440)
# and below pass through untouched; only a source TALLER than this is downscaled,
# and only down to this cap — so a 1080p master stays 1080p and a 4K master
# becomes ~1440p instead of a needlessly huge 2160p file.
MAX_EXPORT_HEIGHT = 1440


# ── Kept-segment math (pure) ──────────────────────────────────────────────────


def kept_segments(
    removed: list[list[float]] | list[tuple[float, float]],
    duration: float,
) -> list[tuple[float, float]]:
    """The complement of ``removed`` over ``[0, duration]`` — the kept material.

    ``removed`` is the merged removed-range list (``removed_ranges`` output:
    sorted, non-overlapping). This walks the gaps between removed spans and the
    head/tail. Spans are clamped to ``[0, duration]`` first so an edge that
    overran the real media length (proxy vs source duration drift, a stale
    hand-edited range) can't produce a negative or out-of-bounds segment. Gaps
    shorter than ``_EPS`` are dropped (a zero-length kept sliver is not a real
    cut point and would only make ffmpeg emit an empty segment).

    Returns ``[(start, end), …]`` in order. An empty list means nothing is kept
    (everything removed) — the caller must treat that as an error, not render it.
    """
    if duration <= 0:
        return []

    # Clamp + drop empties, then sort. We re-sort defensively even though
    # removed_ranges already returns sorted output: this function is also unit-
    # tested with raw/unsorted input, and sorting is cheap (cut counts are small).
    clamped: list[tuple[float, float]] = []
    for a, b in removed:
        a = max(0.0, min(float(a), duration))
        b = max(0.0, min(float(b), duration))
        if b - a > _EPS:
            clamped.append((a, b))
    clamped.sort(key=lambda s: s[0])

    kept: list[tuple[float, float]] = []
    prev = 0.0
    for a, b in clamped:
        if a > prev + _EPS:
            kept.append((prev, a))
        prev = max(prev, b)
    if duration > prev + _EPS:
        kept.append((prev, duration))
    return kept


@dataclass
class ClampResult:
    """Word-clamped removed spans plus the cuts we couldn't fully word-protect.

    ``spans`` is the safe removed list to render. ``unsafe`` counts cuts rendered
    with an edge that could not be lifted clear of a *real* spoken word — kept
    at the user's original edge rather than discarded (the never-drop guarantee),
    and surfaced so the UI can flag them. ``unsafe_spans`` is those original
    edges, for logging/inspection.
    """

    spans: list[tuple[float, float]]
    unsafe: int = 0
    unsafe_spans: list[tuple[float, float]] = field(default_factory=list)


def _edge_in_real_word(
    t: float, spans: list[tuple[float, float]], silences: list[Silence]
) -> bool:
    """True if ``t`` sits inside a spoken word that is NOT measured dead air.

    Forced alignment emits multi-second garbage "words" over pauses (on #4, a
    2.7 s "the" spanning a breath). The aligner's word boundary is meaningless
    there. The audio is the ground truth: if ``t`` lands in MEASURED silence it
    is a clean cut point no matter what label the aligner stuck on it, so it is
    NOT a real-word edge. Only an edge inside a word AND on actual sound is one
    we must move.
    """
    return _inside_word(t, spans) and not edge_lands_in_silence(t, silences)


def _mostly_silence(a: float, b: float, silences: list[Silence]) -> bool:
    """True if measured silence covers most (>60%) of the span ``[a, b]``.

    The test for "this cut is really dead air the aligner mislabeled as a word."
    Such a cut is legitimate and must be honored at the user's own edges even
    when edge-snapping to the bogus word boundary would collapse it.
    """
    span = b - a
    if span <= _EPS or not silences:
        return False
    covered = 0.0
    for sil in silences:
        lo = max(a, sil.start)
        hi = min(b, sil.end)
        if hi > lo:
            covered += hi - lo
    return covered >= 0.6 * span


def _place_edge(
    t: float,
    spans: list[tuple[float, float]],
    silences: list[Silence],
    safety: float,
    *,
    leading: bool,
) -> float:
    """Word-safe position for one cut edge, with the AUDIO as ground truth.

    A cut's start keeps the word BEFORE it and its end keeps the word AFTER it,
    so the only edge we ever move is one sitting on actual SOUND inside a word:

      * edge in measured silence, or in an inter-word gap → already a clean cut
        point; leave it exactly where the user put it. (A forced-alignment
        artifact — a multi-second "word" over a pause — is silence here, so its
        bogus boundary is ignored, which is the whole fix.)
      * edge on real SOUND inside a word → slide it to where the audio says the
        sound stops, not to the aligner's (often oversized) word box. The aligner
        frequently swallows the trailing pause into the word, so its boundary can
        be far past the real voicing; the measured silence inside the word is the
        true offset. A ``leading`` start moves FORWARD to the next in-word silence
        START (sound offset); a trailing end moves BACK to the previous in-word
        silence END (sound onset). Only when the word has no measured silence
        inside it (a genuinely solid word) do we fall back to its hard boundary
        (margined; bare boundary if the cushion hits a butt-joined neighbour).

    Returns the placed time.
    """
    if not _edge_in_real_word(t, spans, silences):
        return t
    cw = _containing_word(t, spans)
    if cw is None:  # defensive; _edge_in_real_word implies a containing word
        return t
    ws, we = cw

    if leading:
        # Forward to the start of the first silence after t but within the word
        # (where the voicing actually stops). Clean cut point, no clip.
        cands = sorted(s.start for s in silences if t <= s.start < we)
        for c in cands:
            if not _edge_in_real_word(c, spans, silences):
                return c
    else:
        # Back to the end of the last silence before t but within the word.
        cands = sorted((s.end for s in silences if ws < s.end <= t), reverse=True)
        for c in cands:
            if not _edge_in_real_word(c, spans, silences):
                return c

    # No in-word silence to land on (a solid, genuinely-spoken word): clear the
    # whole word at its boundary. Margin first; bare boundary if the cushion
    # reaches an overlapping/butt-joined neighbour.
    margined = we + safety if leading else ws - safety
    if not _edge_in_real_word(margined, spans, silences):
        return margined
    return we if leading else ws


def clamp_removed_to_words(
    removed: list[list[float]] | list[tuple[float, float]],
    words: list[dict],
    safety: float = 0.005,
    silences: list[Silence] | None = None,
) -> ClampResult:
    """Pull every removed span's edges out of any *real* spoken word they sit in.

    The word-safety primitive for the AUTO cut bucket (pacing / brain / injected
    micro-cuts) — applied by ``finalize_removed_ranges`` and the injected-micro
    serve guard, NOT to user-drawn spans (those render verbatim). The cut is the
    source of truth: word-safety may *nudge* an edge off a real spoken word, it
    must never *delete* the decision.

    Per cut ``[a, b]``, with the audio as ground truth (see ``_place_edge``):

      1. Place each edge. An edge in measured silence or an inter-word gap is
         already a clean cut point and is LEFT where the user put it — including
         an edge inside a forced-alignment artifact (a multi-second "word" over a
         breath; on #4 a 2.7 s "the"), which reads as silence, so its bogus
         boundary is ignored. Only an edge on actual SOUND inside a real word is
         pushed clear of that word (margin, else hard boundary).
      2. If the placed edges leave a non-empty, word-safe cut → keep it.
      3. If placement collapses the cut (both edges in one real word, or
         butt-joined words snapping to ``s == e``), the user's decision still
         stands: render the ORIGINAL edges and count the cut ``unsafe`` so the
         response can flag it — NEVER drop it silently. (A cut that is mostly
         measured dead air is the aligner's mislabel and is honored the same
         way.) The only thing discarded is a genuinely zero-length INPUT span
         (``b - a <= _EPS``), which removes nothing.

    Spoken words only; ``type == "event"`` vocalizations are excluded by
    ``_word_spans`` and protected elsewhere.

    Returns a ``ClampResult`` (``kept_segments`` re-sorts ``spans``).
    """
    sils = silences or []
    spans = _word_spans(words)
    if not spans:
        # No word timing → nothing to clamp against; pass the ranges through.
        return ClampResult(spans=[(float(a), float(b)) for a, b in removed])

    safe: list[tuple[float, float]] = []
    unsafe_spans: list[tuple[float, float]] = []
    for a, b in removed:
        a, b = float(a), float(b)
        if b - a <= _EPS:
            # Degenerate zero-length input — removes nothing; the only droppable
            # case. (Real cuts always have duration; this is a stray/empty range.)
            continue

        s = _place_edge(a, spans, sils, safety, leading=True)
        e = _place_edge(b, spans, sils, safety, leading=False)
        if e - s > _EPS and not _edge_in_real_word(s, spans, sils) \
                and not _edge_in_real_word(e, spans, sils):
            # Onset tightening: pull the resume (e) onto the next word's measured
            # onset and the outgoing edge (s) onto the previous word's offset, so
            # the kept audio joins ON the voice with no leading dead air and no
            # clipped first phoneme. This clamp now runs ONLY on AUTO micro-cuts
            # (finalize_removed_ranges routes user spans + beats AROUND it, rendered
            # verbatim), and both the serve and export feed the same auto bucket
            # through here, so what the editor draws and what exports agree. Edges
            # only move to word BOUNDARIES, so this never re-enters a real word (the
            # guard above holds). refine_onsets takes/returns the {start,end} shape.
            r = refine_onsets([{"start": s, "end": e}], words)[0]
            rs, re_ = float(r["start"]), float(r["end"])
            if re_ - rs > _EPS and not _edge_in_real_word(rs, spans, sils) \
                    and not _edge_in_real_word(re_, spans, sils):
                s, e = rs, re_
            safe.append((s, e))
            continue

        # Placement collapsed the cut (both edges in one real word, or butt-
        # joined snap to s == e). Honor the user's decision rather than drop it:
        # render the ORIGINAL edges and flag it unsafe.
        if _mostly_silence(a, b, sils):
            logger.info(
                "Honoring dead-air cut %.3f–%.3f at original edges "
                "(forced alignment mislabeled the pause as a word)", a, b,
            )
        else:
            logger.info(
                "Keeping un-word-safe removed span %.3f–%.3f at original edges "
                "(flagged); never dropping a user cut", a, b,
            )
        safe.append((a, b))
        unsafe_spans.append((a, b))

    return ClampResult(spans=safe, unsafe=len(unsafe_spans), unsafe_spans=unsafe_spans)


def _merge_spans(spans: list[tuple[float, float]]) -> list[list[float]]:
    """Merge ``[start, end]`` spans into sorted, non-overlapping intervals.

    The 00-CONTRACT merge, identical to ``editor_server.merge_ranges`` (same
    ``_EPS`` == ``_MERGE_EPS``) — kept here so ``render`` does not import
    ``editor_server`` (that would be a cycle). Drops sub-epsilon slivers, sorts by
    start, and coalesces a span that starts within ``_EPS`` of the running end.
    """
    cleaned = [s for s in spans if (s[1] - s[0]) > _EPS]
    cleaned.sort(key=lambda s: s[0])
    out: list[list[float]] = []
    for s, e in cleaned:
        if out and s <= out[-1][1] + _EPS:
            out[-1][1] = max(out[-1][1], e)
        else:
            out.append([float(s), float(e)])
    return out


@dataclass
class FinalizedRanges:
    """The one removed set both the editor and the export render, plus the flag.

    ``ranges`` is the merged, sorted, non-overlapping removed list (the
    00-CONTRACT set). ``unsafe`` counts AUTO micro-cuts that could not be lifted
    clear of a real spoken word (kept at their edges, never dropped) — surfaced
    so the UI can flag them. User-drawn spans are never counted here: they are
    rendered verbatim and a geometric word-clip is surfaced separately (the
    triage flag), not silently moved.
    """

    ranges: list[list[float]]
    unsafe: int = 0
    unsafe_spans: list[tuple[float, float]] = field(default_factory=list)


def finalize_removed_ranges(
    auto_spans: list[list[float]] | list[tuple[float, float]],
    verbatim_spans: list[list[float]] | list[tuple[float, float]],
    words: list[dict],
    *,
    silences: list[Silence] | None = None,
    safety: float = 0.005,
) -> FinalizedRanges:
    """The single shared "finalize" path the SERVE and the EXPORT both run.

    WYSIWYG hinges on the editor and the export computing the SAME removed set
    from the same saved edit. They do it by calling THIS, with the same two
    buckets, so the result is identical by construction:

      * ``auto_spans`` — machine-chosen micro-cuts (pacing / brain / injected).
        Word-safety + onset-refine apply (``clamp_removed_to_words``): an edge is
        lifted clear of any real spoken word (the fix that stopped the 46 %
        cut-drop) and tightened onto the bordering word onset/offset so the kept
        audio resumes ON the voice. Idempotent on already-safe cuts, so running it
        on both paths costs nothing and guarantees agreement.
      * ``verbatim_spans`` — user-drawn spans (``userRanges`` / ``userCutWords``)
        and the story BEATS. Rendered EXACTLY where they are, with NO clamp and NO
        onset-move: a hand-drawn cut at 300.37 exports at 300.37, never nudged to
        a nearby word boundary. A user cut that clips a word is surfaced by the
        geometric triage flag for the user to fix, not silently relocated. Beats
        ride here too because the editor shows them raw (the JS ``removedRanges``
        mirror never clamps a beat), so the export must not clamp one either.

    Both buckets are merged into one sorted, non-overlapping list. Returns the
    set plus the AUTO-only ``unsafe`` count/spans for flagging.
    """
    clamp = clamp_removed_to_words(
        auto_spans, words, safety=safety, silences=silences or []
    )
    merged = _merge_spans(
        list(clamp.spans) + [(float(a), float(b)) for a, b in verbatim_spans]
    )
    return FinalizedRanges(
        ranges=merged, unsafe=clamp.unsafe, unsafe_spans=clamp.unsafe_spans
    )


# ── ffmpeg filter graph (pure) ────────────────────────────────────────────────

# Audio de-click fade at each cut join. A hard audio splice butts two non-zero
# samples together; that step discontinuity is the "click/pop" Ashley hears
# (feedback #2). A short cosine gain ramp at the join removes the step. 20 ms is
# the sweet spot: long enough to kill the click (well above a single-sample
# discontinuity), short enough to be INAUDIBLE as a fade (a spoken syllable is
# ~150-250 ms, so 20 ms is a hair off the edge). Per-segment `afade` (not
# `acrossfade`) so the fade lives INSIDE each kept segment's own window: it
# changes sample VALUES only, never segment LENGTH or position — so the kept-
# segment math and A-V sync are untouched (acrossfade would overlap segments and
# drift audio against the hard-cut video across ~290 joins). Mirrors the proven
# longform.build_edit_filter / review.py fade pattern. VIDEO stays a hard cut.
AUDIO_JOIN_FADE = 0.02


def build_filter_complex(
    kept: list[tuple[float, float]], fade: float = AUDIO_JOIN_FADE
) -> str:
    """The trim+concat ``filter_complex`` for the kept segments.

    For each kept segment i: ``trim``/``atrim`` to [start,end] then reset the
    timestamps (``setpts``/``asetpts=PTS-STARTPTS``) so the segment starts at 0;
    finally concat all K segments back-to-back into ``[outv][outa]``. This is the
    spike's exact graph (frame-accurate, re-encoded) — see module docstring.

    Audio de-click (``fade``, default 20 ms): every INTERIOR join gets a short
    ``afade=t=out`` on the outgoing segment's tail and a ``afade=t=in`` on the
    incoming segment's head, so the splice ramps instead of stepping (no click).
    The first segment gets no fade-in and the last no fade-out — those are the
    real start/end of the export, not joins. A fade is skipped when the segment is
    too short to host it cleanly: an INTERIOR segment carries BOTH a fade-in and a
    fade-out, so it needs room for two (``dur > 2*fade``) or the in-ramp and the
    out-ramp would overlap and the gain would dip in the middle — an audible notch
    in kept speech; a first/last segment carries only one fade, so ``dur > fade``
    suffices (and keeps ``st=dur-fade`` non-negative). The fade is applied to the
    AUDIO chain only; the VIDEO trim is an untouched hard cut, and because
    ``afade`` reshapes gain within the segment's existing window it shifts no
    timestamps — A-V sync and the kept-segment durations are unchanged.

    Raises ``ValueError`` on empty input: a render with zero kept segments has no
    output and must be caught upstream, not handed to ffmpeg.
    """
    if not kept:
        raise ValueError("no kept segments — nothing to render")

    n = len(kept)
    parts: list[str] = []
    for i, (s, e) in enumerate(kept):
        dur = e - s
        parts.append(f"[0:v]trim=start={s:.3f}:end={e:.3f},setpts=PTS-STARTPTS[v{i}]")
        # atrim → rezero PTS, then de-click fades on the interior join edges.
        achain = f"[0:a]atrim=start={s:.3f}:end={e:.3f},asetpts=PTS-STARTPTS"
        wants_in = i > 0           # not the first seg → fade IN its head
        wants_out = i < n - 1      # not the last seg → fade OUT its tail
        # A segment that hosts BOTH fades needs twice the room, else the two ramps
        # overlap (a mid-segment gain dip). One-fade edge segments need 1×.
        min_dur = (2 if (wants_in and wants_out) else 1) * fade
        if fade > 0 and dur > min_dur:
            if wants_in:
                achain += f",afade=t=in:st=0:d={fade:.3f}"
            if wants_out:
                achain += f",afade=t=out:st={dur - fade:.3f}:d={fade:.3f}"
        achain += f"[a{i}]"
        parts.append(achain)
    concat_in = "".join(f"[v{i}][a{i}]" for i in range(n))
    parts.append(f"{concat_in}concat=n={n}:v=1:a=1[outv][outa]")
    return ";".join(parts)


def scale_filter_for(height: int, max_height: int = MAX_EXPORT_HEIGHT) -> str | None:
    """A ``scale`` filter string when the source must be downscaled, else None.

    Resolution policy: never upscale; only downscale a source TALLER than
    ``max_height``, and only down to the cap. ``-2`` keeps the aspect ratio and
    forces an even width (libx264 + yuv420p needs even dimensions). Returns None
    when ``height`` is at/under the cap — the common case (1080p → no scaling).
    """
    if height <= 0 or height <= max_height:
        return None
    return f"scale=-2:{max_height}"


def build_ffmpeg_cmd(
    source: Path,
    out_path: Path,
    kept: list[tuple[float, float]],
    *,
    source_height: int = 0,
    crf: int = 19,
    progress_url: str | None = None,
) -> list[str]:
    """Assemble the full ffmpeg argv for the export.

    YouTube-sane encode: libx264 **High** profile, ``-pix_fmt yuv420p``, the
    given ``crf`` (18–20), AAC ``-b:a 192k``, ``-movflags +faststart``. When the
    source exceeds the height cap a ``scale`` is appended to the kept-segment
    graph (between concat and the output map) so the downscale happens once on
    the concatenated stream. ``progress_url`` (e.g. ``pipe:2`` or a file path)
    routes ffmpeg ``-progress`` machine output for the status poller.
    """
    fc = build_filter_complex(kept)

    scale = scale_filter_for(source_height)
    if scale:
        # Re-label concat's video out, scale it, then map the scaled label.
        fc = fc.replace("[outv][outa]", "[outv0][outa]")
        fc += f";[outv0]{scale}[outv]"

    cmd = ["ffmpeg", "-y"]
    if progress_url:
        # -progress emits key=value lines (out_time_us=…, progress=continue|end)
        # to the given target; -nostats silences the human stderr spam.
        cmd += ["-nostats", "-progress", progress_url]
    cmd += [
        "-i", str(source),
        "-filter_complex", fc,
        "-map", "[outv]", "-map", "[outa]",
        "-c:v", "libx264", "-preset", "medium", "-profile:v", "high",
        "-crf", str(crf), "-pix_fmt", "yuv420p",
        "-c:a", "aac", "-b:a", "192k",
        "-movflags", "+faststart",
        str(out_path),
    ]
    return cmd


# ── Full-resolution source resolution ─────────────────────────────────────────


def _video_dimensions(path: Path) -> tuple[int, int]:
    """(width, height) of a video's first stream via ffprobe; (0, 0) on failure.

    Best-effort and side-effect free: any ffprobe error (missing file, not a
    video, ffprobe absent) yields (0, 0) so callers can rank candidates without
    crashing the resolver.
    """
    try:
        out = subprocess.run(
            [
                "ffprobe", "-v", "error", "-select_streams", "v:0",
                "-show_entries", "stream=width,height",
                "-of", "csv=s=x:p=0", str(path),
            ],
            capture_output=True, text=True, timeout=30,
        ).stdout.strip()
        w, h = out.split("x")
        return int(w), int(h)
    except Exception:
        return 0, 0


def _candidate_sources(video_path: Path, words_path: Path | None) -> list[Path]:
    """Possible full-res originals for a (possibly-proxy) ``video_path``.

    Probes, in priority order:

      1. ``<video>.source`` sidecar — an explicit, documented override: a text
         file next to the video whose first non-blank line is the source path.
         The escape hatch when the naming convention doesn't apply.
      2. The words-sidecar symlink: ``*-proxy.words.json`` is a symlink to the
         full-res transcript living NEXT TO the original; swap its ``.words.json``
         tail for each known video suffix and test existence. (The real signal in
         this repo — see the redesign dir's symlinks.)
      3. The ``-proxy`` naming convention on the video stem itself, in the same
         directory: ``04-proxy.mp4`` → ``04.<suffix>``.

    Returns existing candidate paths (deduped, order-preserving). The ranking by
    pixel count happens in ``resolve_full_res_source``.
    """
    candidates: list[Path] = []

    def add(p: Path) -> None:
        if p.exists() and p not in candidates:
            candidates.append(p)

    # 1. explicit sidecar override
    sidecar = video_path.with_name(video_path.name + ".source")
    if sidecar.exists():
        try:
            for line in sidecar.read_text(encoding="utf-8").splitlines():
                line = line.strip()
                if line:
                    add(Path(line).expanduser())
                    break
        except OSError:
            logger.warning("Could not read source sidecar %s", sidecar)

    # 2. words-sidecar symlink → original's directory + stem
    if words_path is not None:
        real_words = words_path
        try:
            if words_path.is_symlink():
                real_words = Path(words_path.resolve())
        except OSError:
            real_words = words_path
        # strip the ".words.json" tail to get the source stem+dir, then APPEND a
        # video suffix. (Append, not Path.with_suffix: the stem itself contains
        # dots — "04.The part …" — so with_suffix would mangle it to "04.mp4".)
        name = real_words.name
        if name.endswith(".words.json"):
            base_name = name[: -len(".words.json")]
            for suf in _VIDEO_SUFFIXES:
                add(real_words.with_name(base_name + suf))

    # 3. "-proxy" stem convention in the same directory
    stem = video_path.stem
    for marker in ("-proxy", "_proxy", ".proxy"):
        if stem.endswith(marker):
            base_stem = stem[: -len(marker)]
            for suf in _VIDEO_SUFFIXES:
                add(video_path.with_name(base_stem + suf))
            break

    return candidates


@dataclass
class SourceResolution:
    """The chosen render source and why (surfaced in the API response)."""

    path: Path
    width: int
    height: int
    is_proxy: bool          # True when we upgraded off the editor's video_path
    note: str               # human-readable explanation for the response


def resolve_full_res_source(
    video_path: Path, words_path: Path | None = None
) -> SourceResolution:
    """Pick the highest-resolution source to render from.

    Starts at the editor's ``video_path`` and considers every candidate from
    ``_candidate_sources`` (sidecar / words-symlink / naming convention). Whoever
    has the most pixels wins; ties and total failure fall back to ``video_path``
    so a render is always possible (and the response says so). A candidate only
    displaces ``video_path`` when it is strictly LARGER — never a sideways or
    downward swap.

    DURATION GUARD: the saved cuts are timestamps authored against ``video_path``.
    A candidate is only trusted if its probed duration is within ~0.5s of the
    proxy's — a stem collision (a different, same-named take of a different length)
    would otherwise desync every cut. A length-mismatched candidate is rejected
    with a note; if the proxy's own duration can't be probed there's nothing to
    compare against, so the guard is skipped (pixel ranking stands).
    """
    base_w, base_h = _video_dimensions(video_path)
    base_dur = probe_duration(video_path)
    best = SourceResolution(
        path=video_path,
        width=base_w,
        height=base_h,
        is_proxy=False,
        note=f"rendering from {video_path.name} ({base_w}x{base_h})",
    )

    for cand in _candidate_sources(video_path, words_path):
        if cand == video_path:
            continue
        w, h = _video_dimensions(cand)
        if w * h <= best.width * best.height:
            continue
        # Same-recording check: reject a length-mismatched candidate so a stem
        # collision can't slide every cut against a different-length source.
        if base_dur > 0:
            cand_dur = probe_duration(cand)
            if cand_dur > 0 and abs(cand_dur - base_dur) > 0.5:
                logger.warning(
                    "Skipping full-res candidate %s: duration %.2fs differs from "
                    "proxy %s %.2fs by >0.5s (likely a different take)",
                    cand.name, cand_dur, video_path.name, base_dur,
                )
                continue
        best = SourceResolution(
            path=cand,
            width=w,
            height=h,
            is_proxy=True,
            note=(
                f"upgraded proxy {video_path.name} ({base_w}x{base_h}) → "
                f"full-res {cand.name} ({w}x{h})"
            ),
        )

    if best.is_proxy is False and (base_w, base_h) == (0, 0):
        best.note = (
            f"rendering from {video_path.name} "
            f"(could not probe resolution; no larger source found)"
        )
    return best


# ── Duration probe ────────────────────────────────────────────────────────────


def probe_duration(path: Path) -> float:
    """Media duration in seconds via ffprobe; 0.0 on any failure."""
    try:
        out = subprocess.run(
            [
                "ffprobe", "-v", "error",
                "-show_entries", "format=duration",
                "-of", "default=nw=1:nk=1", str(path),
            ],
            capture_output=True, text=True, timeout=30,
        ).stdout.strip()
        return float(out)
    except Exception:
        return 0.0


# ── Render plan + runner ──────────────────────────────────────────────────────


@dataclass
class RenderPlan:
    """Everything needed to run (and describe) one export, computed up front."""

    source: Path
    out_path: Path
    kept: list[tuple[float, float]]
    removed: list[tuple[float, float]]
    duration: float                 # source duration probed
    out_height: int                 # the export height after the policy cap
    source_width: int
    source_height: int
    source_note: str
    crf: int = 19
    dropped_unsafe: int = 0         # cuts kept at original (un-word-safe) edges
                                    # — surfaced, NEVER silently dropped

    @property
    def kept_duration(self) -> float:
        return sum(e - s for s, e in self.kept)

    @property
    def removed_duration(self) -> float:
        return sum(e - s for s, e in self.removed)

    @property
    def out_resolution(self) -> str:
        """Human label for the EXPORT resolution (``WxH``), honouring the cap.

        Must not pair the source WIDTH with the capped HEIGHT — a 4K source
        (3840x2160) capped to 1440 outputs 2560x1440, not "3840x1440". When the
        height is capped below the source, the width scales with it (``scale=-2``
        keeps the aspect and forces an even width), so we recompute it the same
        way ffmpeg will. At/under the cap (the 1080p case) the source dims pass
        through unchanged.
        """
        if not self.out_height:
            return "source"
        if self.source_height and self.out_height < self.source_height:
            w = round(self.source_width * self.out_height / self.source_height)
            w -= w % 2  # libx264 + yuv420p needs an even width (scale=-2)
            return f"{w}x{self.out_height}"
        return f"{self.source_width}x{self.out_height}"


def build_render_plan(
    *,
    video_path: Path,
    words_path: Path | None,
    removed: list[list[float]] | list[tuple[float, float]],
    words: list[dict],
    out_dir: Path,
    out_name: str,
    crf: int = 19,
    silences: list[Silence] | None = None,
    user_removed: list[list[float]] | list[tuple[float, float]] | None = None,
) -> RenderPlan:
    """Resolve source, finalize the removed set, compute kept segments — pre-flight.

    Pure except for the ffprobe calls (resolution + duration), which are cheap
    and side-effect free.

    The removed set is finalized through the SAME shared path the editor's serve
    side runs (``finalize_removed_ranges``) so the export renders byte-for-byte
    what the editor showed:

      * ``removed``      — the AUTO micro-cuts: word-safety + onset-refine apply
                           (machine-chosen edges can sit mid-word; this is the
                           clamp that stopped the 46 % cut-drop).
      * ``user_removed`` — user-drawn spans (and story beats): rendered VERBATIM,
                           no clamp/onset-move, so a hand-drawn cut exports exactly
                           where it was placed.

    ``silences`` are the MEASURED audio silences (same source the
    ``/api/silences`` endpoint serves); they let the auto word-clamp tell a real
    spoken word from a forced-alignment artifact so a dead-air cut the aligner
    mislabeled as a "word" is honored, not dropped. Raises ``ValueError`` if
    nothing would be kept (every range removed, or a zero/garbage duration) — a
    render with no output is a bug to surface, not a 0-byte file to ship.
    """
    final = finalize_removed_ranges(
        removed, user_removed or [], words, silences=silences
    )
    safe_removed = final.ranges
    dropped = final.unsafe

    src = resolve_full_res_source(video_path, words_path)
    duration = probe_duration(src.path)
    if duration <= 0:
        # Fall back to a word-derived duration so a missing ffprobe still renders
        # (the kept tail just ends at the last word instead of the true media end).
        if words:
            spans = _word_spans(words)
            duration = spans[-1][1] if spans else 0.0
    if duration <= 0:
        raise ValueError("could not determine source duration — cannot render")

    kept = kept_segments(safe_removed, duration)
    if not kept:
        raise ValueError("edit removes the entire video — nothing to render")

    out_height = min(src.height, MAX_EXPORT_HEIGHT) if src.height > 0 else 0

    return RenderPlan(
        source=src.path,
        out_path=out_dir / out_name,
        kept=kept,
        removed=[(float(a), float(b)) for a, b in safe_removed],
        duration=duration,
        out_height=out_height,
        source_width=src.width,
        source_height=src.height,
        source_note=src.note,
        crf=crf,
        dropped_unsafe=dropped,
    )


@dataclass
class RenderProgress:
    """Live state of one render job, shared between the worker and the poller."""

    job_id: str
    status: str = "running"         # running | done | failed
    progress: float = 0.0           # 0..1, parsed from ffmpeg -progress
    output_path: str | None = None
    error: str | None = None
    source_note: str = ""
    kept_segments: int = 0
    removed_total: float = 0.0
    kept_duration: float = 0.0
    out_resolution: str = ""
    dropped_unsafe: int = 0
    extra: dict = field(default_factory=dict)

    def to_dict(self) -> dict:
        return {
            "job_id": self.job_id,
            "status": self.status,
            "progress": round(self.progress, 4),
            "output_path": self.output_path,
            "error": self.error,
            "source_note": self.source_note,
            "kept_segments": self.kept_segments,
            "removed_total": round(self.removed_total, 3),
            "kept_duration": round(self.kept_duration, 3),
            "out_resolution": self.out_resolution,
            "dropped_unsafe": self.dropped_unsafe,
            **self.extra,
        }


def _parse_progress_line(line: str) -> float | None:
    """Pull a fractional-second timestamp out of one ffmpeg ``-progress`` line.

    ffmpeg ``-progress`` emits ``out_time_us=<microseconds>`` (and/or
    ``out_time_ms``, historically misnamed but also microseconds) per update.
    Returns the encoded position in SECONDS, or None for lines that carry no
    timestamp. The caller divides by the kept duration to get 0..1.
    """
    line = line.strip()
    for key, scale in (("out_time_us=", 1e6), ("out_time_ms=", 1e6)):
        if line.startswith(key):
            try:
                return float(line[len(key):]) / scale
            except ValueError:
                return None
    return None


# How much of ffmpeg's drained stderr to retain. Bounded (a rolling tail, not
# an ever-growing accumulator) so a multi-hour render can't grow this without
# limit; comfortably bigger than the 2000 chars actually surfaced on failure.
_STDERR_TAIL_CHARS = 8000


def _drain_stderr(stderr, tail: list[str]) -> None:
    """Read ``stderr`` to EOF on a background thread, keeping only a bounded tail.

    Runs concurrently with the stdout ``-progress`` loop in ``run_render`` so
    ffmpeg's stderr pipe is never left unread (see ``run_render``'s docstring
    for why that deadlocks). Reads in chunks when the stream supports a sized
    ``read`` (real subprocess pipes, unbounded runtime); a simpler stream whose
    ``read()`` takes no size (some test fakes) is read once and stopped there —
    there's no partial-read protocol to loop on. Writes into ``tail[0]`` rather
    than returning, since this runs off-thread; never raises, so a broken fake
    or a mid-read error can't crash or hang the caller.
    """
    try:
        buf = tail[0]
        while True:
            try:
                chunk = stderr.read(4096)
            except TypeError:
                chunk = stderr.read()
                tail[0] = (buf + chunk)[-_STDERR_TAIL_CHARS:]
                return
            if not chunk:
                return
            buf = (buf + chunk)[-_STDERR_TAIL_CHARS:]
            tail[0] = buf
    except Exception:
        pass


def run_render(
    plan: RenderPlan,
    progress: RenderProgress,
    *,
    runner=subprocess.Popen,
) -> None:
    """Execute the encode, streaming ffmpeg ``-progress`` into ``progress``.

    Blocking — call it on a background thread. ``runner`` is the process factory
    (``subprocess.Popen`` in production, a fake in tests) so the heavy encode is
    never actually spawned under unit test. On success ``progress.status`` →
    ``done`` and ``output_path`` is set; any non-zero exit or exception →
    ``failed`` with the tail of ffmpeg's stderr as ``error``. ffmpeg's stderr is
    drained concurrently on a background thread while stdout streams, because an
    unread stderr past the OS pipe buffer would otherwise block ffmpeg's write
    and deadlock the stdout progress loop right along with it.
    """
    plan.out_path.parent.mkdir(parents=True, exist_ok=True)
    cmd = build_ffmpeg_cmd(
        plan.source,
        plan.out_path,
        plan.kept,
        source_height=plan.source_height,
        crf=plan.crf,
        progress_url="pipe:1",  # -progress to stdout; stderr stays human/error
    )

    total = plan.kept_duration or plan.duration or 1.0
    try:
        proc = runner(
            cmd,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
            bufsize=1,
        )
    except FileNotFoundError as exc:
        progress.status = "failed"
        progress.error = f"ffmpeg not found: {exc}"
        return
    except Exception as exc:  # pragma: no cover - defensive
        progress.status = "failed"
        progress.error = str(exc)
        return

    # Drain stderr on its own thread for the whole life of the process — see
    # module docstring / run_render's docstring for why nothing may read stdout
    # only and leave stderr unread.
    stderr_buf: list[str] = [""]
    stderr_thread = None
    if proc.stderr is not None:
        stderr_thread = threading.Thread(
            target=_drain_stderr, args=(proc.stderr, stderr_buf), daemon=True
        )
        stderr_thread.start()

    # Stream stdout (the -progress feed) line by line, updating the fraction.
    if proc.stdout is not None:
        for line in proc.stdout:
            secs = _parse_progress_line(line)
            if secs is not None:
                progress.progress = max(0.0, min(1.0, secs / total))

    proc.wait()
    if stderr_thread is not None:
        stderr_thread.join(timeout=5.0)
    stderr_tail = stderr_buf[0][-2000:]

    if proc.returncode == 0 and plan.out_path.exists():
        progress.progress = 1.0
        progress.status = "done"
        progress.output_path = str(plan.out_path)
    else:
        # A non-zero exit or crash can still leave a TRUNCATED mp4 on disk. Remove
        # it: a half-written file with no moov atom would masquerade as a finished
        # export and the Reveal button would surface a broken video. A failed
        # render must leave NO output behind.
        plan.out_path.unlink(missing_ok=True)
        progress.status = "failed"
        progress.error = (
            f"ffmpeg exited {proc.returncode}: {stderr_tail}"
            if stderr_tail
            else f"ffmpeg exited {proc.returncode}; output not written"
        )
