# GENERATED by studio/tools/sync-engine.sh from hammy/hammy/transcribe.py.
# Do not edit it: change the source and run the script. `sync-engine.sh --check` fails on drift.
"""Transcription backend dispatcher for Hammy."""

import json
import os
import shutil
import subprocess
import tempfile
import warnings
from pathlib import Path
from typing import Optional

# Suppress HF Hub "unauthenticated requests" warning — model is already cached locally
os.environ.setdefault("HF_HUB_DISABLE_IMPLICIT_TOKEN", "1")
warnings.filterwarnings("ignore", message=".*unauthenticated requests.*")
import logging as _logging
_logging.getLogger("huggingface_hub").setLevel(_logging.ERROR)

from lumr_studio.speech import ui

SUPPORTED_EXTENSIONS = {
    ".m4a", ".mp3", ".wav", ".ogg", ".flac",
    ".webm", ".aiff", ".aifc", ".mp4", ".aac",
}
NEEDS_CONVERSION = {".aac", ".mp4", ".aifc", ".aiff", ".webm"}
VIDEO_EXTENSIONS  = {".mp4", ".webm"}


def transcribe_audio(
    audio_path: Path,
    config: dict,
    word_timestamps: bool = False,
) -> tuple[str, str]:
    """Transcribe audio, routing to the correct backend based on config.

    Returns (timestamped_transcript, duration_str).

    When word_timestamps=True, also writes a sidecar JSON file next to
    the audio with per-word timing: [{"word": "...", "start": 0.32, "end": 0.51}, ...]
    """
    platform = config.get("platform") or "mac_silicon"
    package  = config.get("transcription_package") or "mlx-whisper"
    model_id = config.get("transcription_model") or "mlx-community/whisper-large-v3-turbo"

    if platform == "mac_silicon":
        if package == "parakeet-mlx":
            return _transcribe_parakeet_mlx(audio_path, model_id, word_timestamps)
        return _transcribe_mlx_whisper(audio_path, model_id, word_timestamps)
    else:
        if package == "parakeet-nemo":
            return _transcribe_parakeet_nemo(audio_path, model_id, word_timestamps)
        return _transcribe_faster_whisper(audio_path, model_id, word_timestamps)


def _enrich_word_acoustics(
    words: list[dict],
    rms,
    f0_array,
    sr: float,
    hop_length: int,
) -> None:
    """Add per-word acoustic features (energy_rms, pitch_mean) in-place.

    Only enriches speech-word entries (skips events). Frame indices are
    derived from word start/end timestamps and aligned to the RMS and
    f0 arrays. Gracefully handles out-of-bounds and all-NaN slices.
    """
    import numpy as np

    frames_per_sec = sr / hop_length
    for w in words:
        if w.get("type") == "event":
            continue
        f_start = int(w["start"] * frames_per_sec)
        f_end = int(w["end"] * frames_per_sec)

        # Clamp to valid range
        f_start = max(0, f_start)
        f_end = min(len(rms), f_end)

        if f_start < f_end:
            # RMS energy over the word's frame range
            energy = float(np.mean(rms[f_start:f_end]))
            w["energy_rms"] = round(energy, 4)

            # Pitch mean — only non-NaN frames carry pitch
            pitch_slice = f0_array[f_start:f_end]
            valid = pitch_slice[~np.isnan(pitch_slice)]
            if len(valid) > 0:
                w["pitch_mean"] = round(float(np.mean(valid)), 4)
            else:
                w["pitch_mean"] = 0.0
        else:
            w["energy_rms"] = 0.0
            w["pitch_mean"] = 0.0


def _detect_vocalizations(
    audio_path: Path,
    words: list[dict],
    energy_threshold: float = 0.15,
    min_gap: float = 0.2,
    pitch_ratio: float = 0.3,
) -> list[dict]:
    """Detect voiced vocalizations (laughter, gasps, etc.) in gaps between words.

    Analyzes audio energy and pitch during gaps in word timestamps.
    Gaps with high energy AND detectable pitch are tagged as vocalizations.
    """
    try:
        import librosa
        import numpy as np
    except ImportError:
        return []

    try:
        y, sr = librosa.load(str(audio_path), sr=22050, mono=True)
    except Exception:
        return []

    hop_length = 512
    rms = librosa.feature.rms(y=y, frame_length=2048, hop_length=hop_length)[0]

    # Full-audio pitch tracking for per-word acoustic enrichment
    try:
        f0_array, _, _ = librosa.pyin(
            y, fmin=60, fmax=600, sr=sr,
            frame_length=2048, hop_length=hop_length,
        )
    except Exception:
        f0_array = None

    frames_per_sec = sr / hop_length

    speech_energies = []
    for w in words:
        if w.get("type") == "event":
            continue
        f_start = int(w["start"] * frames_per_sec)
        f_end = int(w["end"] * frames_per_sec)
        if f_start < len(rms) and f_end <= len(rms) and f_start < f_end:
            speech_energies.extend(rms[f_start:f_end])

    if not speech_energies:
        return []

    median_speech = float(np.median(speech_energies))
    if median_speech <= 0:
        return []

    threshold = energy_threshold * median_speech
    events = []

    word_entries = [w for w in words if w.get("type") != "event"]
    for i in range(1, len(word_entries)):
        gap_start = word_entries[i - 1]["end"]
        gap_end = word_entries[i]["start"]
        gap_dur = gap_end - gap_start

        if gap_dur < min_gap:
            continue

        f_start = int(gap_start * frames_per_sec)
        f_end = int(gap_end * frames_per_sec)
        if f_start >= len(rms) or f_end > len(rms) or f_start >= f_end:
            continue

        gap_energy = float(np.mean(rms[f_start:f_end]))
        if gap_energy <= threshold:
            continue

        # High energy detected — check for pitch (voiced sound)
        gap_samples_start = int(gap_start * sr)
        gap_samples_end = int(gap_end * sr)
        gap_audio = y[gap_samples_start:gap_samples_end]

        if len(gap_audio) < 2048:
            continue

        f0, voiced_flag, _ = librosa.pyin(
            gap_audio, fmin=60, fmax=600, sr=sr,
            frame_length=2048, hop_length=hop_length,
        )

        if f0 is None or len(f0) == 0:
            continue

        voiced_ratio = float(np.sum(~np.isnan(f0))) / len(f0)
        if voiced_ratio >= pitch_ratio:
            events.append({
                "word": "[vocalization]",
                "start": round(gap_start, 3),
                "end": round(gap_end, 3),
                "type": "event",
            })

    # Enrich words with acoustic features from full-audio analysis
    if f0_array is not None:
        _enrich_word_acoustics(words, rms, f0_array, sr, hop_length)

    return events


def _merge_words_and_events(words: list[dict], events: list[dict]) -> list[dict]:
    """Merge word entries and vocalization events, sorted by start time."""
    combined = words + events
    combined.sort(key=lambda w: w["start"])
    return combined


def _write_word_sidecar(audio_path: Path, words: list[dict]) -> Path:
    """Write word-level timestamps as a JSON sidecar file.

    Returns the path to the written file.
    """
    sidecar_path = audio_path.with_suffix(".words.json")
    with open(sidecar_path, "w", encoding="utf-8") as f:
        json.dump(words, f, ensure_ascii=False, indent=2)
    ui.info(f"Word timestamps saved: {sidecar_path.name}")
    return sidecar_path


def _enforce_monotonic(words: list[dict]) -> list[dict]:
    """Make word timings safe for cutting, in place, without reordering text.

    Guarantees: starts never go backwards, ``end >= start``, a word never
    runs past the next word's start (the earlier end is clamped), and times
    are rounded to 3 places. Returns the same list.
    """
    for i, w in enumerate(words):
        if i > 0 and w["start"] < words[i - 1]["start"]:
            w["start"] = words[i - 1]["start"]
        if w["end"] < w["start"]:
            w["end"] = w["start"]
    for prev, nxt in zip(words, words[1:]):
        if prev["end"] > nxt["start"]:
            prev["end"] = max(prev["start"], nxt["start"])
    for w in words:
        w["start"] = round(w["start"], 3)
        w["end"] = round(w["end"], 3)
    return words


# Gaps shorter than this between two words of the SAME sentence are closed
# (the earlier word's end is stretched to the next word's start). Token end
# times mark when the model emitted the last sub-word on its 80ms frame grid,
# which is usually before the sound of the word stops, so running speech
# shows small false gaps. Left open, _detect_vocalizations finds the
# speaker's own voice in them and reports it as an event.
# Measured on a real 21-minute Parakeet transcript (2974 in-sentence gaps):
# 86% are exactly 0, the 95th percentile is 0.32s, and gaps of 0.3-0.5s
# still produced ~58 voiced "events" in running speech. At 0.5s the total
# was 98 events (45 between sentences, none in a gap under 0.5s); 0.8s gave
# 71 and 1.0s gave 65. Gaps of 0.5s+ mid-sentence are real hesitations
# (often an "um" the model leaves out of the text), so they stay open.
INTRA_SENTENCE_JOIN_GAP = 0.5


def _close_small_gaps(words: list[dict], max_gap: float) -> list[dict]:
    """Stretch each word's end to the next word's start when the gap is < max_gap.

    Assumes ``words`` all belong to one sentence (one continuous phrase) and
    are in text order. Only ends move, and only forward; starts are
    untouched. Returns the same list.
    """
    for prev, nxt in zip(words, words[1:]):
        gap = nxt["start"] - prev["end"]
        if 0 < gap < max_gap:
            prev["end"] = nxt["start"]
    return words


def _match_word_tokens(word: str, toks: list, used: list[bool], prev_time):
    """Consume unused tokens that spell ``word`` left to right.

    At each position, a candidate token's stripped text must match the next
    piece of the word. Preference order: a token whose leading-space flag
    agrees with the position (word-initial piece starts with a space, later
    pieces don't), then the token closest in time to the previous match,
    then the longer piece. A small backtracking search makes sure an early
    choice (" you" for "yourself") doesn't strand the rest of the word; if no
    full spelling exists, the longest greedy prefix is used instead.
    Marks the chosen tokens in ``used``.
    Returns (matched_tokens, fully_matched, last_time).
    """
    budget = [200]  # search nodes; words are short, this is only a safety cap

    def candidates(pos, t_prev, taken):
        found = []
        for i, t in enumerate(toks):
            if used[i] or i in taken:
                continue
            piece = t.text.strip()
            if not word.startswith(piece, pos):
                continue
            boundary_ok = t.text[0].isspace() == (pos == 0)
            dist = abs(t.start - t_prev) if t_prev is not None else t.start
            found.append(((not boundary_ok, dist, -len(piece)), i))
        return [i for _, i in sorted(found)]

    def search(pos, t_prev, taken):
        if pos >= len(word):
            return []
        for i in candidates(pos, t_prev, taken):
            budget[0] -= 1
            if budget[0] < 0:
                return None
            rest = search(pos + len(toks[i].text.strip()), toks[i].start, taken | {i})
            if rest is not None:
                return [i] + rest
        return None

    chosen = search(0, prev_time, frozenset())
    full = chosen is not None
    if not full:  # greedy prefix
        chosen, pos, t_prev = [], 0, prev_time
        while pos < len(word):
            cands = candidates(pos, t_prev, set(chosen))
            if not cands:
                break
            chosen.append(cands[0])
            pos += len(toks[cands[0]].text.strip())
            t_prev = toks[cands[0]].start
    for i in chosen:
        used[i] = True
    matched = [toks[i] for i in chosen]
    return matched, full, (matched[-1].start if matched else prev_time)


def _words_from_sentences(
    sentences, join_gap: float = INTRA_SENTENCE_JOIN_GAP,
) -> tuple[list[dict], dict]:
    """Build word timings where sentence TEXT says what the words are and
    tokens only say when.

    Assumes: each sentence has ``text``, ``start``, ``end`` and ``tokens``
    (objects with ``text``, ``start``, ``end`` and optional ``confidence``).
    parakeet-mlx builds ``sentence.text`` from its merged token stream
    BEFORE sorting ``sentence.tokens`` by start, so the text is in spoken
    order while the token list can be scrambled at 30s chunk seams.

    Per sentence: words are ``text.split()`` in text order. Each word is
    matched to tokens (see ``_match_word_tokens``); its start is the first
    matched token's start, its end the latest end among matched tokens that
    start no earlier than that. Words with no matching token get times
    interpolated between matched neighbours in the same sentence (never
    dropped). Tokens left unused are dropped. Gaps under ``join_gap`` inside
    a sentence are closed, then the whole transcript is made monotonic.

    Returns (words, stats) where stats counts ``matched`` words,
    ``partial`` (matched but some characters had no token),
    ``interpolated`` words and ``dropped_tokens``.
    """
    stats = {"matched": 0, "partial": 0, "interpolated": 0, "dropped_tokens": 0}
    all_words: list[dict] = []

    for sent in sentences:
        text_words = (getattr(sent, "text", "") or "").split()
        toks = [t for t in (getattr(sent, "tokens", None) or [])
                if (getattr(t, "text", "") or "").strip()]
        if not text_words:
            stats["dropped_tokens"] += len(toks)
            continue

        used = [False] * len(toks)
        prev_time = None
        entries: list[Optional[dict]] = []
        for w in text_words:
            matched, full, prev_time = _match_word_tokens(w, toks, used, prev_time)
            if not matched:
                entries.append(None)
                continue
            start = float(matched[0].start)
            end = max(float(t.end) for t in matched if t.start >= start)
            entry = {"word": w, "start": start, "end": end}
            confs = [getattr(t, "confidence", None) for t in matched]
            if all(c is not None for c in confs):
                entry["confidence"] = round(sum(confs) / len(confs), 3)
            entries.append(entry)
            stats["matched" if full else "partial"] += 1
        stats["dropped_tokens"] += used.count(False)

        # Interpolate unmatched runs between their matched neighbours.
        sent_start = float(getattr(sent, "start", 0.0) or 0.0)
        sent_end = max(float(getattr(sent, "end", sent_start) or sent_start), sent_start)
        i = 0
        while i < len(entries):
            if entries[i] is not None:
                i += 1
                continue
            j = i
            while j < len(entries) and entries[j] is None:
                j += 1
            lo = entries[i - 1]["end"] if i > 0 else sent_start
            hi = entries[j]["start"] if j < len(entries) else sent_end
            hi = max(hi, lo)
            step = (hi - lo) / (j - i)
            for k in range(i, j):
                entries[k] = {
                    "word": text_words[k],
                    "start": lo + (k - i) * step,
                    "end": lo + (k - i + 1) * step,
                }
                stats["interpolated"] += 1
            i = j

        all_words.extend(_close_small_gaps(entries, join_gap))

    return _enforce_monotonic(all_words), stats


def _words_from_tokens(tokens) -> list[dict]:
    """Group sub-word ASR tokens into word entries with real timings.

    Assumes: each token has ``text``, ``start`` and ``end`` (seconds) and may
    have ``confidence``. A token whose text starts with whitespace begins a
    new word; tokens without leading whitespace continue the current word.
    This matches parakeet-mlx, whose tokenizer turns the SentencePiece
    word marker "▁" into a leading space.

    Tokens are taken in the order given, so text is never reordered. Use this
    only when there is no sentence text: parakeet-mlx sorts each sentence's
    tokens by start, which scrambles sub-words at chunk seams (use
    ``_words_from_sentences`` there).

    Guarantees: every word has non-empty text, ``end >= start``, starts never
    go backwards, and a word never runs past the next word's start (the
    earlier word's end is clamped). Times are rounded to 3 places;
    ``confidence`` is the mean token confidence, present only when every
    token in the word carries one.
    """
    groups: list[list] = []
    for tok in tokens:
        text = getattr(tok, "text", "") or ""
        if not text.strip():
            # Whitespace-only token: a word boundary with no content.
            if text and groups and groups[-1]:
                groups.append([])
            continue
        if not groups or not groups[-1] or text[0].isspace():
            groups.append([tok])
        else:
            groups[-1].append(tok)

    words: list[dict] = []
    for group in groups:
        if not group:
            continue
        text = "".join(t.text for t in group).strip()
        if not text:
            continue
        entry = {
            "word": text,
            "start": float(group[0].start),
            "end": float(group[-1].end),
        }
        confs = [getattr(t, "confidence", None) for t in group]
        if all(c is not None for c in confs):
            entry["confidence"] = round(sum(confs) / len(confs), 3)
        words.append(entry)

    return _enforce_monotonic(words)


def _synthesize_word_timings(sentences) -> list[dict]:
    """Approximate word-level timings from sentence-level timestamps.

    Distributes words evenly across each sentence's time span. Last resort
    for a backend with no word or token timings: the result is only a guess,
    so a warning is printed every time it is used.

    Each sentence's start is clamped to the previous sentence's end, so
    overlapping sentences can never interleave their words.
    """
    ui.warn(
        "Word timings are APPROXIMATE (spread evenly across each sentence) - "
        "the backend gave no per-word timings. Cuts made from them will be imprecise."
    )
    words = []
    prev_end = None
    for sent in sentences:
        text = sent.text.strip() if hasattr(sent, "text") else str(sent).strip()
        start = sent.start if hasattr(sent, "start") else 0.0
        end = sent.end if hasattr(sent, "end") else start
        tokens = text.split()
        if not tokens:
            continue
        if prev_end is not None and start < prev_end:
            start = prev_end
        end = max(end, start)
        prev_end = end
        duration = end - start
        per_word = duration / len(tokens) if len(tokens) > 0 else duration
        for i, token in enumerate(tokens):
            w_start = start + i * per_word
            w_end = start + (i + 1) * per_word
            words.append({
                "word": token,
                "start": round(w_start, 3),
                "end": round(w_end, 3),
            })
    return words


# ── mlx-whisper (Apple Silicon default) ──────────────────────────────────────

def _transcribe_mlx_whisper(
    audio_path: Path, model_id: str, word_timestamps: bool = False,
) -> tuple[str, str]:
    import mlx_whisper

    transcribe_path = audio_path
    tmp_wav = None
    if audio_path.suffix.lower() in NEEDS_CONVERSION:
        tmp_wav = _convert_to_wav(audio_path)
        if tmp_wav:
            transcribe_path = tmp_wav

    try:
        result = mlx_whisper.transcribe(
            str(transcribe_path),
            path_or_hf_repo=model_id,
            verbose=False,
            word_timestamps=word_timestamps,
        )
    finally:
        if tmp_wav and tmp_wav.exists():
            tmp_wav.unlink()

    if word_timestamps:
        words = []
        for seg in result.get("segments", []):
            for w in seg.get("words", []):
                entry = {
                    "word": w.get("word", "").strip(),
                    "start": round(w.get("start", 0.0), 3),
                    "end": round(w.get("end", 0.0), 3),
                }
                prob = w.get("probability")
                if prob is not None:
                    entry["confidence"] = round(prob, 4)
                words.append(entry)
        # Fallback: synthesize from segment-level timings
        if not words:
            segments = result.get("segments", [])
            if segments:
                _Seg = type("_Seg", (), {})
                synth_sents = []
                for seg in segments:
                    s = _Seg()
                    s.text = seg.get("text", "")
                    s.start = seg.get("start", 0.0)
                    s.end = seg.get("end", 0.0)
                    synth_sents.append(s)
                words = _synthesize_word_timings(synth_sents)
        if words:
            events = _detect_vocalizations(audio_path, words)
            if events:
                ui.info(f"Detected {len(events)} vocalization(s)")
                words = _merge_words_and_events(words, events)
            _write_word_sidecar(audio_path, words)
        else:
            ui.warn(
                "Word timestamps requested but backend returned no word-level data. "
                "The .words.json sidecar was NOT written."
            )

    return _format_segments(result.get("segments", []))


# ── parakeet-mlx (Apple Silicon, English-optimised) ──────────────────────────

def _transcribe_parakeet_mlx(
    audio_path: Path, model_id: str, word_timestamps: bool = False,
) -> tuple[str, str]:
    try:
        import parakeet_mlx
    except ImportError:
        ui.warn("parakeet-mlx not installed — falling back to mlx-whisper.")
        return _transcribe_mlx_whisper(
            audio_path, "mlx-community/whisper-large-v3-turbo", word_timestamps
        )

    transcribe_path = audio_path
    tmp_wav = None
    if audio_path.suffix.lower() in NEEDS_CONVERSION:
        tmp_wav = _convert_to_wav(audio_path)
        if tmp_wav:
            transcribe_path = tmp_wav

    try:
        model = parakeet_mlx.from_pretrained(model_id)
        with ui.transcribe_progress(audio_path.name) as chunk_cb:
            result = model.transcribe(
                str(transcribe_path),
                chunk_duration=30.0,
                chunk_callback=chunk_cb,
            )
    finally:
        if tmp_wav and tmp_wav.exists():
            tmp_wav.unlink()

    # AlignedResult.sentences: list of AlignedSentence with .text, .start, .end
    # and .tokens (AlignedToken: .text, .start, .duration, .end, .confidence).
    # sentence.text keeps spoken order; sentence.tokens is sorted by start,
    # which can scramble sub-words at chunk seams. See _words_from_sentences.
    sentences = result.sentences if result.sentences else []
    if not sentences:
        return "", "0:00"

    if word_timestamps:
        word_data, stats = _words_from_sentences(sentences)
        ui.info(
            f"Word timings: {stats['matched']} matched, {stats['partial']} partial, "
            f"{stats['interpolated']} interpolated, "
            f"{stats['dropped_tokens']} stray token(s) dropped"
        )
        # Last resort: synthesize from sentence-level timings (warns loudly)
        if not word_data and sentences:
            word_data = _synthesize_word_timings(sentences)
        if word_data:
            events = _detect_vocalizations(audio_path, word_data)
            if events:
                ui.info(f"Detected {len(events)} vocalization(s)")
                word_data = _merge_words_and_events(word_data, events)
            _write_word_sidecar(audio_path, word_data)
        else:
            ui.warn(
                "Word timestamps requested but backend returned no word-level data. "
                "The .words.json sidecar was NOT written."
            )

    lines = []
    for sent in sentences:
        start = sent.start
        timestamp = f"[{int(start // 60):02d}:{int(start % 60):02d}]"
        lines.append(f"{timestamp} {sent.text.strip()}")
    last_end = sentences[-1].end
    duration_str = f"{int(last_end // 60)}:{int(last_end % 60):02d}"
    return "\n".join(lines), duration_str


# ── faster-whisper (NVIDIA / AMD / CPU) ──────────────────────────────────────

def _transcribe_faster_whisper(
    audio_path: Path, model_id: str, word_timestamps: bool = False,
) -> tuple[str, str]:
    try:
        from faster_whisper import WhisperModel
    except ImportError:
        raise RuntimeError(
            "faster-whisper not installed. Run: pipx inject hammy faster-whisper"
        )

    transcribe_path = audio_path
    tmp_wav = None
    if audio_path.suffix.lower() in NEEDS_CONVERSION:
        tmp_wav = _convert_to_wav(audio_path)
        if tmp_wav:
            transcribe_path = tmp_wav

    try:
        model = WhisperModel(model_id)
        segments_iter, info = model.transcribe(
            str(transcribe_path),
            word_timestamps=word_timestamps,
        )
        segments = list(segments_iter)
    finally:
        if tmp_wav and tmp_wav.exists():
            tmp_wav.unlink()

    if word_timestamps:
        words = []
        for seg in segments:
            for w in (seg.words or []):
                entry = {
                    "word": w.word.strip(),
                    "start": round(w.start, 3),
                    "end": round(w.end, 3),
                }
                if hasattr(w, "probability") and w.probability is not None:
                    entry["confidence"] = round(w.probability, 4)
                words.append(entry)
        if words:
            events = _detect_vocalizations(audio_path, words)
            if events:
                ui.info(f"Detected {len(events)} vocalization(s)")
                words = _merge_words_and_events(words, events)
            _write_word_sidecar(audio_path, words)
        else:
            ui.warn(
                "Word timestamps requested but backend returned no word-level data. "
                "The .words.json sidecar was NOT written."
            )

    lines = []
    last_end = 0.0
    for seg in segments:
        start = seg.start
        timestamp = f"[{int(start // 60):02d}:{int(start % 60):02d}]"
        lines.append(f"{timestamp} {seg.text.strip()}")
        last_end = seg.end

    transcript = "\n".join(lines)
    duration_str = f"{int(last_end // 60)}:{int(last_end % 60):02d}"
    return transcript, duration_str


# ── parakeet-nemo (NVIDIA GPU) ────────────────────────────────────────────────

def _transcribe_parakeet_nemo(
    audio_path: Path, model_id: str, word_timestamps: bool = False,
) -> tuple[str, str]:
    import logging as _logging
    for _name in ("nemo_logger", "nemo", "nemo.core", "pytorch_lightning"):
        _logging.getLogger(_name).setLevel(_logging.ERROR)

    try:
        import nemo.collections.asr as nemo_asr
    except ImportError:
        raise RuntimeError(
            "nemo-toolkit not installed. Run: pipx inject hammy 'nemo-toolkit[asr]'"
        )

    transcribe_path = audio_path
    tmp_wav = None
    if audio_path.suffix.lower() in NEEDS_CONVERSION:
        tmp_wav = _convert_to_wav(audio_path)
        if tmp_wav:
            transcribe_path = tmp_wav

    try:
        import torch
        asr_model = nemo_asr.models.ASRModel.from_pretrained(model_name=model_id)
        asr_model = asr_model.to("cuda" if torch.cuda.is_available() else "cpu")
        outputs = asr_model.transcribe([str(transcribe_path)], timestamps=True)
    finally:
        if tmp_wav and tmp_wav.exists():
            tmp_wav.unlink()

    result = outputs[0]
    segments = []
    if hasattr(result, "timestamp") and isinstance(result.timestamp, dict):
        segments = result.timestamp.get("segment", [])

    if word_timestamps and hasattr(result, "timestamp") and isinstance(result.timestamp, dict):
        word_data = []
        for w in result.timestamp.get("word", []):
            word_data.append({
                "word": w.get("word", "").strip(),
                "start": round(w.get("start", 0.0), 3),
                "end": round(w.get("end", 0.0), 3),
            })
        if word_data:
            events = _detect_vocalizations(audio_path, word_data)
            if events:
                ui.info(f"Detected {len(events)} vocalization(s)")
                word_data = _merge_words_and_events(word_data, events)
            _write_word_sidecar(audio_path, word_data)
        else:
            ui.warn(
                "Word timestamps requested but backend returned no word-level data. "
                "The .words.json sidecar was NOT written."
            )

    if segments:
        lines = []
        for seg in segments:
            start = seg["start"]
            timestamp = f"[{int(start // 60):02d}:{int(start % 60):02d}]"
            lines.append(f"{timestamp} {seg['segment'].strip()}")
        last_end = segments[-1]["end"]
        duration_str = f"{int(last_end // 60)}:{int(last_end % 60):02d}"
        return "\n".join(lines), duration_str

    text = result.text if hasattr(result, "text") else str(result)
    return text.strip(), "unknown"


# ── Audio conversion ──────────────────────────────────────────────────────────

def _convert_to_wav(audio_path: Path) -> Optional[Path]:
    """Convert audio to 16kHz mono WAV using ffmpeg. Returns temp path or None."""
    if not shutil.which("ffmpeg"):
        ui.warn("ffmpeg not found, skipping conversion.")
        return None
    tmp = tempfile.NamedTemporaryFile(suffix=".wav", delete=False)
    tmp.close()

    commands = [
        ["ffmpeg", "-y", "-c:a", "aac_at", "-i", str(audio_path),
         "-ar", "16000", "-ac", "1", tmp.name],
        ["ffmpeg", "-y", "-err_detect", "ignore_err", "-i", str(audio_path),
         "-ar", "16000", "-ac", "1", tmp.name],
    ]

    for cmd in commands:
        try:
            subprocess.run(cmd, capture_output=True, text=True, timeout=600)
            tmp_path = Path(tmp.name)
            if tmp_path.exists() and tmp_path.stat().st_size > 1000:
                ui.info("Converting audio to hamster-readable format...")
                return tmp_path
        except Exception:
            continue

    ui.warn("Audio conversion failed.")
    if os.path.exists(tmp.name):
        os.unlink(tmp.name)
    return None


# ── Shared formatter ──────────────────────────────────────────────────────────

def _format_segments(segments: list) -> tuple[str, str]:
    """Format mlx-style segment list into (transcript, duration_str)."""
    if not segments:
        return "", "0:00"
    lines = []
    for seg in segments:
        start = seg["start"]
        timestamp = f"[{int(start // 60):02d}:{int(start % 60):02d}]"
        lines.append(f"{timestamp} {seg['text'].strip()}")
    last_end = segments[-1]["end"]
    duration_str = f"{int(last_end // 60)}:{int(last_end % 60):02d}"
    return "\n".join(lines), duration_str
