"""The engine and speech files are copies. These tests hold the copy honest.

``studio/tools/sync-engine.sh`` is the only writer of ``engine/`` and ``speech/``.
Its ``--check`` runs here when the repo's sources are next to the plugin; an
installed copy of the plugin has no sources, so those tests skip there.
"""

import ast
import importlib.util
import subprocess
import sys
from pathlib import Path

import pytest

SERVER_DIR = Path(__file__).resolve().parents[1]
PACKAGE = SERVER_DIR / "lumr_studio"
REPO = SERVER_DIR.parents[3]
SYNC = REPO / "studio" / "tools" / "sync-engine.sh"
HEADER = "# GENERATED by studio/tools/sync-engine.sh from "

GENERATED_FOLDERS = ("engine", "speech")
# The only files in those folders that people write.
HAND_WRITTEN = {"engine/__init__.py", "engine/paths.py", "speech/__init__.py", "speech/__main__.py"}
# A copied file may import a module the plugin doesn't ship, from inside a
# function nothing here calls. This names each one; a new one fails the test.
DEAD_IMPORTS = {
    ("engine/longform.py", "lumr_studio.engine.config"),  # edit_video: ClipForge's own render path
    ("engine/longform.py", "lumr_studio.engine.editor"),
}

needs_repo = pytest.mark.skipif(not SYNC.exists(), reason="no clipforge or hammy sources beside this plugin")


def copied_files() -> list[Path]:
    files = [p for folder in GENERATED_FOLDERS for p in sorted((PACKAGE / folder).glob("*.py"))]
    return [p for p in files if p.relative_to(PACKAGE).as_posix() not in HAND_WRITTEN]


def test_the_copies_are_the_files_the_script_writes():
    names = {p.relative_to(PACKAGE).as_posix() for p in copied_files()}
    assert names == {
        "engine/alignment.py", "engine/audio_boundaries.py", "engine/filler.py",
        "engine/longform.py", "engine/microcut_pacing.py", "engine/render.py",
        "speech/transcribe.py", "speech/ui.py",
    }


@pytest.mark.parametrize("path", copied_files(), ids=lambda p: p.name)
def test_every_copy_says_it_is_generated_and_from_where(path):
    first, second = path.read_text().splitlines()[:2]
    assert first.startswith(HEADER) and first.endswith(".py."), first
    assert "Do not edit" in second
    if SYNC.exists():
        source = first[len(HEADER):-1]
        assert (REPO / source).is_file(), f"{path.name} names a source that isn't there: {source}"


@needs_repo
def test_no_copy_has_drifted_from_its_source():
    done = subprocess.run([str(SYNC), "--check"], capture_output=True, text=True)
    assert done.returncode == 0, done.stdout + done.stderr


def test_nothing_imports_clipforge_or_hammy():
    found = []
    for path in PACKAGE.rglob("*.py"):
        for node in ast.walk(ast.parse(path.read_text())):
            names = [a.name for a in node.names] if isinstance(node, ast.Import) else []
            if isinstance(node, ast.ImportFrom) and node.module and not node.level:
                names = [node.module]
            found += [f"{path.relative_to(PACKAGE)}: {n}" for n in names if n.split(".")[0] in {"clipforge", "hammy"}]
    assert found == []


def _imports_inside_functions(path: Path) -> set[str]:
    """The ``lumr_studio`` modules that ``path`` imports from inside a function."""
    found: set[str] = set()
    for function in ast.walk(ast.parse(path.read_text())):
        if isinstance(function, (ast.FunctionDef, ast.AsyncFunctionDef)):
            for node in ast.walk(function):
                if isinstance(node, ast.ImportFrom) and node.module and node.module.split(".")[0] == "lumr_studio":
                    found.add(node.module)
    return found


def _is_shipped(module: str) -> bool:
    try:
        return importlib.util.find_spec(module) is not None
    except ModuleNotFoundError:
        return False


def test_a_copy_reaches_only_shipped_modules_from_inside_its_functions():
    lacking = {
        (path.relative_to(PACKAGE).as_posix(), module)
        for path in copied_files()
        for module in _imports_inside_functions(path)
        if not _is_shipped(module)
    }
    assert lacking == DEAD_IMPORTS


def test_every_module_loads_when_clipforge_and_hammy_cannot_be_imported():
    # ``sys.modules[name] = None`` makes ``import name`` fail, even where the repo's own packages are installed.
    modules = ["lumr_studio.server"] + [
        f"lumr_studio.{p.relative_to(PACKAGE).with_suffix('').as_posix().replace('/', '.')}"
        for p in copied_files()
    ]
    code = (
        "import importlib, sys\n"
        "sys.modules['clipforge'] = None\n"
        "sys.modules['hammy'] = None\n"
        f"for name in {modules!r}:\n"
        "    importlib.import_module(name)\n"
        "heavy = {m.split('.')[0] for m in sys.modules} & {'torch', 'torchaudio', 'parakeet_mlx'}\n"
        "assert not heavy, f'loaded at import: {heavy}'\n"
    )
    done = subprocess.run([sys.executable, "-c", code], capture_output=True, text=True)
    assert done.returncode == 0, done.stderr
